create extension if not exists pgcrypto;
create table if not exists public.platform (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  name text not null,
  kind text not null check (kind in ('exchange','broker','wallet')),
  status text not null default 'research' check (status in ('research','verified','restricted')),
  short_description text,
  full_review text,
  official_url text,
  affiliate_url text,
  affiliate_partner_id text,
  logo_url text,
  custody_model text,
  tags text[] not null default '{}',
  fee_summary text,
  security_summary text,
  regulatory_summary text,
  product_summary text,
  pros text[] not null default '{}',
  cons text[] not null default '{}',
  seo_title text,
  seo_description text,
  featured boolean not null default false,
  visible boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
