import type{NextConfig}from"next";
const securityHeaders=[{key:"X-Content-Type-Options",value:"nosniff"},{key:"Referrer-Policy",value:"strict-origin-when-cross-origin"},{key:"X-Frame-Options",value:"DENY"},{key:"Permissions-Policy",value:"camera=(), microphone=(), geolocation=(), payment=()"},{key:"Cross-Origin-Opener-Policy",value:"same-origin"},{key:"Strict-Transport-Security",value:"max-age=63072000; includeSubDomains; preload"}];
const nextConfig:NextConfig={
  reactStrictMode:true,
  poweredByHeader:false,
  compress:true,
  distDir: process.env.NEXT_DEV_DIST || ".next",
  experimental:{optimizePackageImports:["lucide-react"]},
  async headers(){return[{source:"/:path*",headers:securityHeaders}]},
  async redirects(){return[
    {source:"/guides",destination:"/learn",permanent:true},
    {source:"/guides/:slug",destination:"/learn/:slug",permanent:true},
    {source:"/cards",destination:"/crypto-cards",permanent:true},
    {source:"/onramps",destination:"/on-ramps",permanent:true},
    {source:"/on-ramp",destination:"/on-ramps",permanent:true},
    {source:"/reward",destination:"/rewards",permanent:true},
    {source:"/nfts",destination:"/nft",permanent:true},
    {source:"/bridge",destination:"/bridges",permanent:true},
    {source:"/copy",destination:"/copy-trading",permanent:true},
    {source:"/l2",destination:"/layer2",permanent:true},
    {source:"/stablecoin",destination:"/stablecoins",permanent:true},
    {source:"/kyc",destination:"/identity",permanent:true},
    {source:"/yield-farming",destination:"/yield",permanent:true},
    {source:"/discover",destination:"/niches",permanent:true},
    {source:"/start-here",destination:"/start",permanent:true},
    {source:"/help",destination:"/faq",permanent:true},
    {source:"/use-cases",destination:"/jobs",permanent:true},
    {source:"/options-trading",destination:"/options",permanent:true},
    {source:"/eigenlayer",destination:"/restaking",permanent:true},
    {source:"/real-world-assets",destination:"/rwa",permanent:true},
    {source:"/prediction-markets",destination:"/prediction",permanent:true},
    {source:"/lend",destination:"/lending",permanent:true},
    {source:"/socialfi",destination:"/social",permanent:true},
    {source:"/crypto-etf",destination:"/etf",permanent:true},
    {source:"/earn",destination:"/savings",permanent:true},
    {source:"/topics-map",destination:"/topics",permanent:true},
    {source:"/nodes",destination:"/rpc",permanent:true},
    {source:"/travel-rule",destination:"/compliance",permanent:true},
    {source:"/crypto-index",destination:"/indexes",permanent:true},
    {source:"/structured-products",destination:"/structured",permanent:true},
    {source:"/indexes-etf",destination:"/indexes",permanent:true},
    {source:"/faq-page",destination:"/faq",permanent:true},
    {source:"/get-started",destination:"/start",permanent:true},
    {source:"/otc-desk",destination:"/otc",permanent:true},
    {source:"/portfolio-tracker",destination:"/portfolio",permanent:true},
    {source:"/trading-bots",destination:"/bots",permanent:true},
    {source:"/crypto-payroll",destination:"/payroll",permanent:true},
    {source:"/token-vesting",destination:"/vesting",permanent:true},
    {source:"/market-making",destination:"/liquidity",permanent:true},
    {source:"/crypto-education",destination:"/education",permanent:true},
    {source:"/price-alerts",destination:"/alerts",permanent:true},
    {source:"/how-we-research",destination:"/methodology",permanent:true},
    {source:"/fx",destination:"/forex",permanent:true},
    {source:"/prop-firms",destination:"/prop",permanent:true},
    {source:"/charts",destination:"/charting",permanent:true},
    {source:"/mpc",destination:"/multisig",permanent:true},
  ]},
};
export default nextConfig;
