import Link from "next/link";
import { ArrowUpRight, BookOpen, ChevronRight, CircleDollarSign, Fingerprint, Globe2, Landmark, LockKeyhole, Radar, ShieldCheck, SlidersHorizontal, WalletCards, Waves, Zap } from "lucide-react";
import { SITE_NAME } from "@/lib/site";
import { buildMetadata, webPageJsonLd } from "@/lib/seo";
export const metadata=buildMetadata({title:`${SITE_NAME} — Digital Asset & Trading Research`,description:"A large-format research portal for crypto exchanges, brokers, wallets, fees, security and market access.",path:"/",keywords:["crypto exchange research","broker comparison","crypto wallet comparison","crypto fees","trading platform research"]});
const tracks=[
 {id:"A",eyebrow:"VENUES",title:"Crypto exchanges",copy:"Research spot and derivatives venues through fees, custody, liquidity, security and jurisdiction-specific access.",href:"/exchanges",icon:<Waves/>},
 {id:"B",eyebrow:"MARKET ACCESS",title:"Online brokers",copy:"Separate research for forex, CFDs and multi-asset brokers — with entity, product and risk context kept explicit.",href:"/brokers",icon:<Landmark/>},
 {id:"C",eyebrow:"CUSTODY",title:"Wallet systems",copy:"Hardware, software and self-custody tools examined through ownership, recovery, compatibility and security design.",href:"/wallets",icon:<WalletCards/>}
];
const briefs=[
 ["01","Fees are not one number","Trading fee, spread, funding and withdrawal cost belong in separate evidence fields.","/learn/crypto-fees-explained"],
 ["02","Custody changes the risk model","An exchange account and a self-custody wallet solve different problems and expose different failure modes.","/learn/exchange-vs-wallet"],
 ["03","Market access is local","A platform, feature or promotion can be available in one jurisdiction and restricted in another.","/markets"],
 ["04","Broker ≠ exchange","Execution model, instruments, custody and legal structure must not be collapsed into one generic score.","/learn/broker-vs-exchange"]
];
export default function Home(){const schema=webPageJsonLd({name:`${SITE_NAME} digital asset research`,description:"Independent research across exchanges, brokers, wallets and market access.",path:"/"});return <main className="portal-home"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
<section className="portal-hero"><div className="hero-gridlines"/><div className="portal-hero-copy"><span className="portal-index">AXIOM / RESEARCH NETWORK / 2026</span><h1>Markets are noisy.<br/><em>Structure isn’t.</em></h1><p>One independent research layer for digital-asset venues, brokers, wallets, fees, security and jurisdiction-specific access.</p><div className="portal-actions"><Link href="/exchanges">Explore research <ArrowUpRight/></Link><Link href="/how-we-rate">Read our protocol</Link></div><div className="portal-proof"><span><Fingerprint/> evidence-first</span><span><Globe2/> market-aware</span><span><ShieldCheck/> risk-context</span></div></div><div className="portal-hero-art"><div className="orbit o1"/><div className="orbit o2"/><div className="orbit o3"/><div className="portal-core"><Radar/><b>AXIOM</b><small>INTELLIGENCE GRID</small></div><span className="node node-a">FEES</span><span className="node node-b">CUSTODY</span><span className="node node-c">ACCESS</span><span className="node node-d">RISK</span></div></section>
<section className="portal-strip"><span>EXCHANGE RESEARCH</span><b>•</b><span>BROKER INTELLIGENCE</span><b>•</b><span>WALLET SECURITY</span><b>•</b><span>FEE ANALYSIS</span><b>•</b><span>MARKET ACCESS</span></section>
<section className="portal-intro"><div><span className="portal-index">01 / RESEARCH MAP</span><h2>Different products.<br/>Different questions.</h2></div><p>Axiom Grid does not force every financial product into the same affiliate-card template. Each research track has its own evidence model, comparison logic and editorial context.</p></section>
<section className="portal-tracks">{tracks.map((x,i)=><Link href={x.href} className={`track track-${i+1}`} key={x.id}><span className="track-id">{x.id}</span><i>{x.icon}</i><small>{x.eyebrow}</small><h3>{x.title}</h3><p>{x.copy}</p><b>Open desk <ArrowUpRight/></b></Link>)}</section>
<section className="portal-method"><div className="method-visual"><div className="method-axis"><span>IDENTITY</span><span>SECURITY</span><span>COST</span><span>ACCESS</span><span>DISCLOSURE</span></div><div className="method-card"><small>RESEARCH OBJECT / 001</small><strong>Evidence<br/>before ranking.</strong><p>Unknown data stays unknown. Commercial relationships do not manufacture facts.</p></div></div><div className="method-copy"><span className="portal-index">02 / METHODOLOGY</span><h2>A research system that can show its work.</h2><p>Profiles are designed around source-backed facts, dated checks, category-specific criteria and visible limitations. This creates a better foundation for comparisons than a single unexplained star score.</p><div className="method-points"><span><Fingerprint/> Source identity</span><span><LockKeyhole/> Security & custody</span><span><CircleDollarSign/> Cost structure</span><span><Globe2/> Market eligibility</span></div><Link href="/how-we-rate">Full methodology <ArrowUpRight/></Link></div></section>
<section className="portal-briefs"><div className="briefs-head"><span className="portal-index">03 / FIELD NOTES</span><h2>Understand the system,<br/>not just the logo.</h2><Link href="/learn">All guides <ArrowUpRight/></Link></div><div className="brief-list">{briefs.map(x=><Link href={x[3]} key={x[0]}><span>{x[0]}</span><div><h3>{x[1]}</h3><p>{x[2]}</p></div><ChevronRight/></Link>)}</div></section>
<section className="portal-markets"><div className="market-copy"><span className="portal-index">04 / JURISDICTIONS</span><h2>Global brand.<br/>Local reality.</h2><p>Products, entities, permissions and commercial eligibility can change by country. Market pages are built to keep those differences visible rather than hiding them behind a global claim.</p><Link href="/markets">Explore market architecture <ArrowUpRight/></Link></div><div className="market-matrix"><div><span>01</span><b>PLATFORM</b><em>What is the product?</em></div><div><span>02</span><b>ENTITY</b><em>Who provides it locally?</em></div><div><span>03</span><b>ACCESS</b><em>What can users actually use?</em></div><div><span>04</span><b>PROMOTION</b><em>Can a commercial CTA appear?</em></div><div><span>05</span><b>EVIDENCE</b><em>When was it checked?</em></div></div></section>
<section className="portal-lab"><div className="lab-top"><span>AXIOM GRID / RESEARCH LAB</span><span>PUBLIC SYSTEM</span></div><div className="lab-body"><div><Zap/><span>COMPARE</span><h3>Build decisions from comparable facts.</h3><Link href="/compare">Comparison desk <ArrowUpRight/></Link></div><div><SlidersHorizontal/><span>FEES</span><h3>Separate headline fees from real cost layers.</h3><Link href="/fees">Cost research <ArrowUpRight/></Link></div><div><ShieldCheck/><span>SECURITY</span><h3>Track custody, controls, incidents and disclosures.</h3><Link href="/security">Security desk <ArrowUpRight/></Link></div><div><BookOpen/><span>LEARN</span><h3>Long-form explainers built around user questions.</h3><Link href="/learn">Knowledge base <ArrowUpRight/></Link></div></div></section>
<section className="portal-final"><span className="portal-index">05 / TRANSPARENCY</span><h2>No mystery rankings.<br/>No hidden methodology.</h2><p>Axiom Grid is being built as a research publication first. Affiliate relationships, when present, are disclosed and kept separate from factual verification.</p><div><Link href="/editorial-policy">Editorial policy</Link><Link href="/legal/affiliate-disclosure">Affiliate disclosure</Link><Link href="/about">About Axiom Grid</Link></div></section>
</main>}
