import Link from "next/link";
import { ArrowUpRight, BarChart3, Bitcoin, Bot, ChartNoAxesCombined, ChevronRight, CircleDollarSign, Cpu, Fingerprint, Globe2, Landmark, LockKeyhole, Radar, Route, ShieldCheck, Sparkles, WalletCards, Waves } from "lucide-react";
import { SITE_NAME } from "@/lib/site";
import { buildMetadata, webPageJsonLd } from "@/lib/seo";
export const metadata=buildMetadata({title:`${SITE_NAME} — Crypto, Trading & Digital Asset Intelligence`,description:"Independent research for crypto exchanges, brokers, wallets, fees, market access and trading infrastructure.",path:"/",keywords:["crypto exchange research","broker comparison","crypto wallet research","trading platform comparison"]});

const lanes=[
 {n:"01",icon:<Bitcoin/>,title:"Exchange layer",copy:"Spot, derivatives, funding rails and centralized crypto venues.",href:"/exchanges",meta:"TRADE / LIQUIDITY"},
 {n:"02",icon:<ChartNoAxesCombined/>,title:"Broker layer",copy:"Forex, CFDs and multi-asset trading access — kept separate from exchanges.",href:"/brokers",meta:"MARKETS / EXECUTION"},
 {n:"03",icon:<WalletCards/>,title:"Custody layer",copy:"Hardware, software and self-custody systems for asset control.",href:"/wallets",meta:"WALLETS / SECURITY"}
];

export default function Home(){const schema=webPageJsonLd({name:`${SITE_NAME} market intelligence`,description:"Independent crypto, broker and wallet research.",path:"/"});return <main className="ag-home"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
<section className="ag-hero"><div className="ag-hero-noise"/><div className="ag-hero-left"><div className="ag-kicker"><span className="pulse"/> DIGITAL ASSET INTELLIGENCE / 2026</div><h1>Read the market<br/><span>before the market</span><br/>reads you.</h1><p>One research system for exchanges, brokers, wallets, market access, fees and risk context. No casino-style ranking grid. No product types mixed together.</p><div className="ag-hero-cta"><Link href="/exchanges">Enter the grid <ArrowUpRight/></Link><Link href="/how-we-rate">Research protocol</Link></div></div>
<div className="ag-hero-right"><div className="ag-radar"><span className="ring r1"/><span className="ring r2"/><span className="ring r3"/><span className="axis x"/><span className="axis y"/><span className="scan"/><i className="dot d1"/><i className="dot d2"/><i className="dot d3"/><div className="radar-center"><Radar/><b>AXIOM</b><small>RESEARCH NODE</small></div></div><div className="ag-float-note n1"><LockKeyhole/> custody map</div><div className="ag-float-note n2"><Globe2/> geo eligibility</div><div className="ag-float-note n3"><Waves/> market signal</div></div></section>

<section className="ag-ticker"><div>MARKET STRUCTURE <b>EXCHANGES</b></div><div>PRODUCT TYPE <b>BROKERS</b></div><div>CUSTODY <b>WALLETS</b></div><div>DECISION LAYER <b>COMPARE</b></div><div>JURISDICTION <b>MARKETS</b></div></section>

<section className="ag-lanes"><div className="ag-section-marker">01 — CHOOSE A LAYER</div>{lanes.map(l=><Link href={l.href} className="ag-lane" key={l.n}><div className="lane-num">{l.n}</div><div className="lane-icon">{l.icon}</div><div className="lane-copy"><small>{l.meta}</small><h2>{l.title}</h2><p>{l.copy}</p></div><ChevronRight className="lane-arrow"/></Link>)}</section>

<section className="ag-split"><div className="ag-split-copy"><div className="ag-section-marker">02 — THE RESEARCH ENGINE</div><h2>Designed like a market terminal, not an affiliate catalogue.</h2><p>Every public profile is meant to move through evidence, product classification, market eligibility and disclosure before a commercial CTA can exist.</p><Link href="/how-we-rate">Open methodology <ArrowUpRight/></Link></div><div className="ag-system-map"><div className="sys-row"><span>01</span><b><Fingerprint/> Identity</b><em>official source / legal entity</em></div><div className="sys-row"><span>02</span><b><ShieldCheck/> Risk</b><em>custody / incidents / protection</em></div><div className="sys-row"><span>03</span><b><CircleDollarSign/> Cost</b><em>fees / spread / funding</em></div><div className="sys-row"><span>04</span><b><Globe2/> Market</b><em>availability / promotion status</em></div><div className="sys-row"><span>05</span><b><Route/> Route</b><em>review / compare / affiliate CTA</em></div></div></section>

<section className="ag-console"><div className="console-head"><span>AXIOM GRID // PUBLIC RESEARCH FEED</span><span>LIVE ARCHITECTURE</span></div><div className="console-grid"><div className="console-main"><div className="terminal-line"><span>→</span> Public brand listings are intentionally empty until reviewed in the admin control room.</div><div className="terminal-line"><span>→</span> Exchange, broker and wallet records are published independently.</div><div className="terminal-line"><span>→</span> Market eligibility is fail-closed by default.</div><div className="terminal-line accent"><span>→</span> Next: onboard verified partners and evidence sources.</div></div><div className="console-side"><div><Bot/><span>RESEARCH QUEUE</span><b>ADMIN</b></div><div><Cpu/><span>AUTOMATION</span><b>READY</b></div><div><BarChart3/><span>SEO LAYER</span><b>ACTIVE</b></div></div></div></section>

<section className="ag-bottom-cta"><Sparkles/><div><span>CONTROL THE INVENTORY</span><h2>Platforms enter from the admin, not from hard-coded demo cards.</h2></div><Link href="/admin">Open control room <ArrowUpRight/></Link></section>
</main>}
