import {NextRequest,NextResponse} from "next/server";
import {createClient} from "@supabase/supabase-js";
import {isAdminUser} from "@/lib/supabase/admin";
import {assertSafeEditorialCopy} from "@/lib/contentSafety";
function db(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)return null;return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
const arr=(v:any)=>Array.isArray(v)?v.map(String).map(x=>x.trim().toUpperCase()).filter(Boolean):String(v||"").split(/[,\n]/).map(x=>x.trim().toUpperCase()).filter(Boolean);
const slugify=(v:string)=>v.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
export async function GET(){if(!(await isAdminUser()))return NextResponse.json({ok:false,error:"Unauthorized"},{status:401});const s=db();if(!s)return NextResponse.json({ok:false,error:"Supabase is not configured.",items:[]},{status:503});const{data,error}=await s.from("partner_post").select("*,platform:platform_id(name)").order("updated_at",{ascending:false});return error?NextResponse.json({ok:false,error:error.message,items:[]},{status:500}):NextResponse.json({ok:true,items:data||[]})}
export async function POST(req:NextRequest){if(!(await isAdminUser()))return NextResponse.json({ok:false,error:"Unauthorized"},{status:401});const s=db();if(!s)return NextResponse.json({ok:false,error:"Supabase is not configured."},{status:503});const b=await req.json().catch(()=>({}));const title=String(b.title||"").trim(),body=String(b.body||"").trim(),excerpt=String(b.excerpt||"").trim(),platform_id=String(b.platform_id||"").trim(),source_url=String(b.source_url||"").trim();if(!title||!body||!platform_id||!source_url)return NextResponse.json({ok:false,error:"Platform, title, body and an official/source URL are required."},{status:400});const safety=assertSafeEditorialCopy(title,excerpt,body);if(!safety.safe)return NextResponse.json({ok:false,error:`Copy blocked by claim-safety rules: ${safety.reasons.join(", ")}. Rephrase as a factual update without guarantees or absolute rankings.`},{status:400});const slug=String(b.slug||slugify(title)).trim();const published=Boolean(b.published);const payload={platform_id,slug,title,excerpt:excerpt||null,body,post_type:["partner_update","bonus_update","product_update","market_update","editorial_note"].includes(String(b.post_type))?String(b.post_type):"partner_update",bonus_label:String(b.bonus_label||"").trim()||null,terms_summary:String(b.terms_summary||"").trim()||null,source_url,market_codes:arr(b.market_codes),published,published_at:published?(b.published_at||new Date().toISOString()):null,valid_until:b.valid_until||null,seo_title:String(b.seo_title||"").trim()||null,seo_description:String(b.seo_description||"").trim()||null,updated_at:new Date().toISOString()};const id=String(b.id||"").trim();const q=id?s.from("partner_post").update(payload).eq("id",id).select("*").single():s.from("partner_post").insert(payload).select("*").single();const{data,error}=await q;return error?NextResponse.json({ok:false,error:error.message},{status:500}):NextResponse.json({ok:true,item:data})}
export async function DELETE(req:NextRequest){if(!(await isAdminUser()))return NextResponse.json({ok:false,error:"Unauthorized"},{status:401});const id=req.nextUrl.searchParams.get("id");const s=db();if(!s||!id)return NextResponse.json({ok:false,error:"Missing id"},{status:400});const{error}=await s.from("partner_post").delete().eq("id",id);return error?NextResponse.json({ok:false,error:error.message},{status:500}):NextResponse.json({ok:true})}
