export const PLATFORM_KIND_IDS = [
  "exchange",
  "dex",
  "broker",
  "trading-platform",
  "wallet",
  "defi",
  "staking",
  "crypto-card",
  "onramp",
  "tool",
  "explorer",
  "tax",
  "futures",
  "copy-trading",
  "p2p",
  "nft",
  "launchpad",
  "bridge",
  "yield",
  "insurance",
  "custody",
  "identity",
  "analytics",
  "mining",
  "layer2",
  "payments",
  "institutional",
  "dao",
  "oracle",
  "validator",
  "stablecoin",
  "options",
  "restaking",
  "rwa",
  "prediction",
  "lending",
  "privacy",
  "gamefi",
  "social",
  "etf",
  "savings",
  "rpc",
  "compliance",
  "index",
  "structured",
  "otc",
  "portfolio",
  "bots",
  "payroll",
  "vesting",
  "liquidity",
  "education",
  "alerts",
] as const;

export type PlatformKind = (typeof PLATFORM_KIND_IDS)[number];

export type AttributeField = {
  key: string;
  label: string;
  type: "bool" | "text";
};

export type CatalogKind = {
  id: PlatformKind;
  hub: string;
  label: string;
  plural: string;
  group: string;
  dedicated: boolean;
  summary: string;
  subcategories: string[];
  attributes: AttributeField[];
  compareKeys: string[];
};

const bool = (key: string, label: string): AttributeField => ({ key, label, type: "bool" });
const text = (key: string, label: string): AttributeField => ({ key, label, type: "text" });

export const CATALOG: CatalogKind[] = [
  {
    id: "exchange",
    hub: "exchanges",
    label: "Centralized exchange",
    plural: "Exchanges",
    group: "Trading venues",
    dedicated: true,
    summary: "Custodial spot and derivatives venues researched by product scope, fees, funding, security context and market eligibility.",
    subcategories: ["spot", "derivatives", "hybrid"],
    attributes: [
      bool("spot", "Spot trading"),
      bool("margin", "Margin"),
      bool("futures", "Futures"),
      bool("options", "Options"),
      bool("staking", "Staking / earn"),
      bool("p2p", "P2P"),
      bool("fiat", "Fiat support"),
      bool("api", "Public API"),
      bool("tradingview", "TradingView integration"),
      bool("mobile_app", "Mobile app"),
      text("kyc", "KYC (as published)"),
    ],
    compareKeys: ["custody", "feeSummary", "spot", "futures", "margin", "staking", "fiat", "api", "mobile_app", "kyc"],
  },
  {
    id: "dex",
    hub: "dex",
    label: "Decentralized exchange",
    plural: "DEXs",
    group: "Trading venues",
    dedicated: false,
    summary: "Non-custodial swap and order-book protocols compared only on disclosed networks, custody model and published mechanics.",
    subcategories: ["amm", "order-book", "aggregator"],
    attributes: [
      bool("spot", "Spot / swap"),
      bool("perps", "Perpetuals"),
      bool("aggregator", "Aggregator"),
      text("networks", "Networks (as published)"),
      bool("open_source", "Open-source (if stated)"),
    ],
    compareKeys: ["custody", "networks", "spot", "perps", "open_source", "securitySummary"],
  },
  {
    id: "broker",
    hub: "brokers",
    label: "Broker",
    plural: "Brokers",
    group: "Trading venues",
    dedicated: true,
    summary: "Forex, CFD and multi-asset brokers reviewed by legal entity, instruments, cost disclosures and market access — not mixed with spot crypto venues.",
    subcategories: ["forex", "cfd", "multi-asset"],
    attributes: [
      bool("forex", "Forex"),
      bool("cfd", "CFDs"),
      bool("crypto_cfd", "Crypto CFDs"),
      bool("mt4", "MT4"),
      bool("mt5", "MT5"),
      text("kyc", "Onboarding (as published)"),
    ],
    compareKeys: ["feeSummary", "regulatorySummary", "forex", "cfd", "mt4", "mt5", "kyc"],
  },
  {
    id: "trading-platform",
    hub: "trading",
    label: "Trading platform",
    plural: "Trading platforms",
    group: "Trading venues",
    dedicated: false,
    summary: "Execution front-ends and multi-venue terminals compared by disclosed connectivity, instruments and custody relationship.",
    subcategories: ["terminal", "social", "copy"],
    attributes: [
      bool("spot", "Spot"),
      bool("futures", "Futures"),
      bool("api", "API"),
      bool("tradingview", "TradingView"),
      bool("mobile_app", "Mobile app"),
      bool("desktop_app", "Desktop app"),
    ],
    compareKeys: ["productSummary", "spot", "futures", "api", "mobile_app", "desktop_app"],
  },
  {
    id: "wallet",
    hub: "wallets",
    label: "Wallet",
    plural: "Wallets",
    group: "Custody",
    dedicated: true,
    summary: "Hardware, software, mobile and web wallets compared by custody, recovery, chain support and what the user actually controls.",
    subcategories: ["hardware", "software", "mobile", "browser", "custodial"],
    attributes: [
      bool("hardware", "Hardware device"),
      bool("mobile_app", "Mobile app"),
      bool("desktop_app", "Desktop app"),
      bool("browser_extension", "Browser extension"),
      bool("swap", "Built-in swap"),
      bool("staking", "Staking"),
      bool("nft", "NFT support"),
      bool("open_source", "Open-source (if stated)"),
      text("networks", "Networks (as published)"),
    ],
    compareKeys: ["custody", "hardware", "mobile_app", "browser_extension", "swap", "staking", "nft", "networks", "open_source"],
  },
  {
    id: "defi",
    hub: "defi",
    label: "DeFi platform",
    plural: "DeFi platforms",
    group: "On-chain",
    dedicated: false,
    summary: "On-chain apps researched from public documentation only. Yields and TVL are never invented.",
    subcategories: ["lending", "liquidity", "other"],
    attributes: [
      bool("lending", "Lending"),
      bool("swap", "Swap"),
      bool("staking", "Staking / lockups"),
      text("networks", "Networks (as published)"),
      bool("open_source", "Open-source (if stated)"),
    ],
    compareKeys: ["custody", "networks", "lending", "swap", "staking", "open_source"],
  },
  {
    id: "staking",
    hub: "staking",
    label: "Staking / earn",
    plural: "Staking & earn",
    group: "On-chain",
    dedicated: false,
    summary: "Earn and staking products compared on custody, lockups and disclosed terms. APY is only shown when a sourced figure exists.",
    subcategories: ["native", "liquid", "custodial-earn"],
    attributes: [
      bool("liquid_staking", "Liquid staking"),
      bool("custodial_earn", "Custodial earn"),
      text("lockup", "Lockup (as published)"),
      text("networks", "Networks (as published)"),
    ],
    compareKeys: ["custody", "liquid_staking", "custodial_earn", "lockup", "networks", "feeSummary"],
  },
  {
    id: "crypto-card",
    hub: "crypto-cards",
    label: "Crypto card",
    plural: "Crypto cards",
    group: "Payments",
    dedicated: false,
    summary: "Spend cards compared on issuer, custody of the underlying balance, fees and published market eligibility.",
    subcategories: ["debit", "credit"],
    attributes: [
      bool("fiat", "Fiat settlement"),
      text("networks", "Card network (as published)"),
      text("kyc", "KYC (as published)"),
    ],
    compareKeys: ["custody", "feeSummary", "fiat", "kyc", "regulatorySummary"],
  },
  {
    id: "onramp",
    hub: "on-ramps",
    label: "On/off-ramp",
    plural: "On/off-ramps",
    group: "Payments",
    dedicated: false,
    summary: "Fiat ramps compared on published payment rails, KYC and destination assets — never by guessed country coverage.",
    subcategories: ["on-ramp", "off-ramp", "both"],
    attributes: [
      bool("onramp", "Buy crypto"),
      bool("offramp", "Sell crypto"),
      text("rails", "Payment rails (as published)"),
      text("kyc", "KYC (as published)"),
    ],
    compareKeys: ["onramp", "offramp", "rails", "kyc", "feeSummary"],
  },
  {
    id: "tool",
    hub: "tools",
    label: "Trading / analytics tool",
    plural: "Tools",
    group: "Tools",
    dedicated: false,
    summary: "Bots, trackers and data tools compared on disclosed features. Market prices are never simulated here.",
    subcategories: ["bot", "portfolio", "analytics", "security"],
    attributes: [
      bool("bot", "Automation / bot"),
      bool("portfolio", "Portfolio tracking"),
      bool("analytics", "Analytics / data"),
      bool("api", "API"),
      bool("mobile_app", "Mobile app"),
    ],
    compareKeys: ["bot", "portfolio", "analytics", "api", "mobile_app", "productSummary"],
  },
  {
    id: "explorer",
    hub: "explorers",
    label: "Blockchain explorer",
    plural: "Explorers",
    group: "Infrastructure",
    dedicated: false,
    summary: "Block explorers and chain browsers compared on disclosed networks, APIs and what they actually index — never simulated chain data.",
    subcategories: ["l1", "l2", "multi-chain"],
    attributes: [
      bool("api", "Public API"),
      text("networks", "Networks (as published)"),
      bool("analytics", "Analytics views"),
    ],
    compareKeys: ["networks", "api", "analytics", "productSummary"],
  },
  {
    id: "tax",
    hub: "tax",
    label: "Crypto tax / accounting",
    plural: "Tax & accounting",
    group: "Tools",
    dedicated: false,
    summary: "Tax and accounting products compared on published jurisdictions, import methods and reporting scope. This is not tax advice.",
    subcategories: ["tax", "accounting", "bookkeeping"],
    attributes: [
      bool("api", "API / CSV import"),
      text("kyc", "Account requirements (as published)"),
      bool("mobile_app", "Mobile app"),
    ],
    compareKeys: ["kyc", "api", "mobile_app", "productSummary", "regulatorySummary"],
  },
  {
    id: "futures",
    hub: "futures",
    label: "Perpetuals / futures venue",
    plural: "Futures & perps",
    group: "Trading venues",
    dedicated: false,
    summary: "Perpetual and dated futures venues compared on custody, published contract specs and market access. Funding rates are never invented.",
    subcategories: ["perps", "dated", "options"],
    attributes: [
      bool("futures", "Dated futures"),
      bool("perps", "Perpetuals"),
      bool("options", "Options"),
      bool("api", "Public API"),
      text("kyc", "KYC (as published)"),
    ],
    compareKeys: ["custody", "futures", "perps", "options", "api", "feeSummary", "kyc"],
  },
  {
    id: "copy-trading",
    hub: "copy-trading",
    label: "Copy / social trading",
    plural: "Copy trading",
    group: "Trading venues",
    dedicated: false,
    summary: "Copy and social trading products compared on who you follow, custody of the copied account, and published fees. Past results are never shown as forecasts.",
    subcategories: ["copy", "social", "signals"],
    attributes: [
      bool("mobile_app", "Mobile app"),
      bool("api", "API / signals"),
      text("kyc", "Onboarding (as published)"),
    ],
    compareKeys: ["custody", "feeSummary", "mobile_app", "kyc", "productSummary"],
  },
  {
    id: "p2p",
    hub: "p2p",
    label: "P2P marketplace",
    plural: "P2P markets",
    group: "Payments",
    dedicated: false,
    summary: "Peer-to-peer crypto marketplaces compared on escrow, payment rails and published dispute process. Escrow is not the same as exchange custody.",
    subcategories: ["escrow", "otc"],
    attributes: [
      bool("fiat", "Fiat rails"),
      text("kyc", "KYC (as published)"),
      text("rails", "Payment methods (as published)"),
    ],
    compareKeys: ["custody", "fiat", "rails", "kyc", "feeSummary"],
  },
  {
    id: "nft",
    hub: "nft",
    label: "NFT marketplace",
    plural: "NFT markets",
    group: "On-chain",
    dedicated: false,
    summary: "NFT marketplaces compared on custody of the item, fees and published networks. Floor prices and volume are never fabricated.",
    subcategories: ["marketplace", "aggregator"],
    attributes: [
      bool("nft", "NFT trading"),
      text("networks", "Networks (as published)"),
      bool("open_source", "Open-source (if stated)"),
    ],
    compareKeys: ["custody", "networks", "feeSummary", "nft", "open_source"],
  },
  {
    id: "launchpad",
    hub: "launchpads",
    label: "Launchpad / token sale",
    plural: "Launchpads",
    group: "On-chain",
    dedicated: false,
    summary: "Token sale and launchpad products compared on eligibility, custody of committed funds and published terms. Allocations are never invented.",
    subcategories: ["ido", "ieo", "launchpad"],
    attributes: [
      text("kyc", "Eligibility (as published)"),
      bool("staking", "Stake-to-join (if stated)"),
      text("networks", "Networks (as published)"),
    ],
    compareKeys: ["custody", "kyc", "staking", "networks", "productSummary"],
  },
  {
    id: "bridge",
    hub: "bridges",
    label: "Cross-chain bridge",
    plural: "Bridges",
    group: "Infrastructure",
    dedicated: false,
    summary: "Bridges compared on published chains, custody of in-flight assets and documented failure modes. TVL and speed claims stay empty unless sourced.",
    subcategories: ["lock-mint", "liquidity", "canonical"],
    attributes: [
      text("networks", "Networks (as published)"),
      bool("open_source", "Open-source (if stated)"),
    ],
    compareKeys: ["custody", "networks", "open_source", "securitySummary", "feeSummary"],
  },
  {
    id: "yield",
    hub: "yield",
    label: "Yield aggregator",
    plural: "Yield aggregators",
    group: "On-chain",
    dedicated: false,
    summary: "Yield routers compared on custody of deposits, published strategies and lockups. APY is shown only when a sourced figure exists.",
    subcategories: ["vault", "auto-compound"],
    attributes: [
      bool("lending", "Lending routes"),
      bool("staking", "Staking routes"),
      text("networks", "Networks (as published)"),
      text("lockup", "Lockup (as published)"),
    ],
    compareKeys: ["custody", "networks", "lending", "staking", "lockup", "feeSummary"],
  },
  {
    id: "insurance",
    hub: "insurance",
    label: "Crypto insurance / cover",
    plural: "Insurance & cover",
    group: "Security",
    dedicated: false,
    summary: "On-chain and commercial cover products compared on what is actually insured, who pays claims and published exclusions. Cover is not a guarantee.",
    subcategories: ["protocol", "custodial", "wallet"],
    attributes: [
      text("kyc", "Eligibility (as published)"),
      bool("open_source", "Open-source (if stated)"),
    ],
    compareKeys: ["productSummary", "kyc", "regulatorySummary", "securitySummary"],
  },
  {
    id: "custody",
    hub: "custody",
    label: "Institutional custody",
    plural: "Custody providers",
    group: "Custody",
    dedicated: false,
    summary: "Qualified and institutional custodians compared on who holds keys, bankruptcy remoteness as published, and market eligibility. This is not legal advice.",
    subcategories: ["qualified", "prime", "segregated"],
    attributes: [
      bool("api", "API / settlement"),
      text("kyc", "Onboarding (as published)"),
    ],
    compareKeys: ["custody", "regulatorySummary", "securitySummary", "kyc", "api"],
  },
  {
    id: "identity",
    hub: "identity",
    label: "Identity / KYC provider",
    plural: "Identity & KYC",
    group: "Tools",
    dedicated: false,
    summary: "KYC and identity vendors compared on published checks and data handling. TopPick does not score how “easy” onboarding feels.",
    subcategories: ["kyc", "kyb", "attestation"],
    attributes: [
      bool("api", "API"),
      text("kyc", "Checks (as published)"),
    ],
    compareKeys: ["kyc", "api", "regulatorySummary", "productSummary"],
  },
  {
    id: "analytics",
    hub: "analytics",
    label: "On-chain analytics",
    plural: "Analytics desks",
    group: "Tools",
    dedicated: false,
    summary: "Analytics and data desks compared on disclosed sources and networks. Charts here never pretend to be a live market feed.",
    subcategories: ["on-chain", "portfolio", "terminal"],
    attributes: [
      bool("analytics", "Analytics views"),
      bool("api", "API"),
      bool("mobile_app", "Mobile app"),
      text("networks", "Networks (as published)"),
    ],
    compareKeys: ["analytics", "api", "networks", "mobile_app", "productSummary"],
  },
  {
    id: "mining",
    hub: "mining",
    label: "Mining pool / hardware",
    plural: "Mining",
    group: "Infrastructure",
    dedicated: false,
    summary: "Pools and mining products compared on payout method, custody of rewards and published fees. Hashprice is never invented.",
    subcategories: ["pool", "hardware", "cloud"],
    attributes: [
      bool("api", "API / stats"),
      text("networks", "Coins / networks (as published)"),
    ],
    compareKeys: ["feeSummary", "networks", "api", "productSummary"],
  },
  {
    id: "layer2",
    hub: "layer2",
    label: "Layer 2 / scaling",
    plural: "Layer 2",
    group: "Infrastructure",
    dedicated: false,
    summary: "L2 and scaling networks compared on published security model, bridges and documented operators. Throughput numbers stay empty unless sourced.",
    subcategories: ["rollup", "sidechain", "validium"],
    attributes: [
      text("networks", "Base / stack (as published)"),
      bool("open_source", "Open-source (if stated)"),
    ],
    compareKeys: ["networks", "open_source", "securitySummary", "productSummary"],
  },
  {
    id: "payments",
    hub: "payments",
    label: "Crypto payments",
    plural: "Crypto payments",
    group: "Payments",
    dedicated: false,
    summary: "Merchant and payout rails compared on settlement asset, custody of float and published markets. Processing volume is never fabricated.",
    subcategories: ["merchant", "payout", "invoice"],
    attributes: [
      bool("fiat", "Fiat settlement"),
      text("kyc", "Merchant KYC (as published)"),
      bool("api", "API"),
    ],
    compareKeys: ["custody", "fiat", "kyc", "api", "feeSummary"],
  },
  {
    id: "institutional",
    hub: "institutional",
    label: "Prime / institutional desk",
    plural: "Institutional desks",
    group: "Trading venues",
    dedicated: false,
    summary: "Prime brokerage and OTC desks compared on published counterparties, custody and onboarding. Quotes and inventory are never invented.",
    subcategories: ["prime", "otc", "credit"],
    attributes: [
      bool("api", "FIX / API"),
      text("kyc", "Onboarding (as published)"),
    ],
    compareKeys: ["custody", "regulatorySummary", "kyc", "api", "productSummary"],
  },
  {
    id: "dao",
    hub: "dao",
    label: "DAO tooling",
    plural: "DAO tools",
    group: "On-chain",
    dedicated: false,
    summary: "Governance and DAO tools compared on voting custody, treasuries and published networks. Token prices are not shown as performance.",
    subcategories: ["governance", "treasury", "multisig"],
    attributes: [
      text("networks", "Networks (as published)"),
      bool("open_source", "Open-source (if stated)"),
    ],
    compareKeys: ["custody", "networks", "open_source", "productSummary"],
  },
  {
    id: "oracle",
    hub: "oracles",
    label: "Oracle / data feed",
    plural: "Oracles",
    group: "Infrastructure",
    dedicated: false,
    summary: "Oracle networks compared on published feeds, update model and documented operators. Live prices are never simulated on TopPick.",
    subcategories: ["price", "vrf", "automation"],
    attributes: [
      text("networks", "Networks (as published)"),
      bool("open_source", "Open-source (if stated)"),
      bool("api", "API / feeds"),
    ],
    compareKeys: ["networks", "api", "open_source", "securitySummary"],
  },
  {
    id: "validator",
    hub: "validators",
    label: "Validator / node operator",
    plural: "Validators",
    group: "Infrastructure",
    dedicated: false,
    summary: "Validators and node operators compared on published networks, slashing treatment and custody of staked assets. APR is only shown when sourced.",
    subcategories: ["validator", "rpc", "node"],
    attributes: [
      text("networks", "Networks (as published)"),
      text("lockup", "Bond / lockup (as published)"),
    ],
    compareKeys: ["custody", "networks", "lockup", "feeSummary", "securitySummary"],
  },
  {
    id: "stablecoin",
    hub: "stablecoins",
    label: "Stablecoin issuer",
    plural: "Stablecoins",
    group: "Payments",
    dedicated: false,
    summary: "Stablecoin issuers compared on reserve disclosures, redemption and published markets. Peg strength is never scored from a chart we do not source.",
    subcategories: ["fiat-backed", "crypto-backed", "algorithmic"],
    attributes: [
      bool("fiat", "Fiat redemption (if stated)"),
      text("networks", "Networks (as published)"),
    ],
    compareKeys: ["regulatorySummary", "fiat", "networks", "productSummary", "securitySummary"],
  },
  {
    id: "options",
    hub: "options",
    label: "Options desk",
    plural: "Options",
    group: "Trading venues",
    dedicated: false,
    summary: "Crypto and listed options desks compared on contract type, custody of collateral and published expiries. Greeks and implied vol are never simulated.",
    subcategories: ["vanilla", "exotic", "listed"],
    attributes: [
      bool("options", "Options"),
      bool("api", "API"),
      text("kyc", "Onboarding (as published)"),
    ],
    compareKeys: ["custody", "options", "api", "kyc", "feeSummary", "regulatorySummary"],
  },
  {
    id: "restaking",
    hub: "restaking",
    label: "Restaking protocol",
    plural: "Restaking",
    group: "On-chain",
    dedicated: false,
    summary: "Restaking and shared-security products compared on what is restaked, who can slash, and published operators. Points and APY stay empty unless sourced.",
    subcategories: ["eigenlayer", "liquid", "operator"],
    attributes: [
      text("networks", "Networks (as published)"),
      text("lockup", "Lockup / undelegate (as published)"),
      bool("open_source", "Open-source (if stated)"),
    ],
    compareKeys: ["custody", "networks", "lockup", "open_source", "securitySummary"],
  },
  {
    id: "rwa",
    hub: "rwa",
    label: "Tokenized / RWA product",
    plural: "RWAs",
    group: "On-chain",
    dedicated: false,
    summary: "Tokenized funds, treasuries and real-world assets compared on the legal wrapper, custody of the off-chain asset and published markets. Yield is never invented.",
    subcategories: ["treasury", "credit", "fund"],
    attributes: [
      text("kyc", "Eligibility (as published)"),
      text("networks", "Networks (as published)"),
    ],
    compareKeys: ["custody", "kyc", "regulatorySummary", "networks", "productSummary"],
  },
  {
    id: "prediction",
    hub: "prediction",
    label: "Prediction market",
    plural: "Prediction markets",
    group: "Trading venues",
    dedicated: false,
    summary: "Event and prediction markets compared on resolution source, custody of stakes and published eligibility. Odds are not shown as live tape.",
    subcategories: ["event", "sports", "politics"],
    attributes: [
      text("kyc", "Eligibility (as published)"),
      bool("fiat", "Fiat settlement (if stated)"),
    ],
    compareKeys: ["custody", "kyc", "fiat", "regulatorySummary", "productSummary"],
  },
  {
    id: "lending",
    hub: "lending",
    label: "Lending / borrow market",
    plural: "Lending",
    group: "On-chain",
    dedicated: false,
    summary: "Lending and borrow markets compared on collateral, liquidation and who holds the asset. Supply APY is only shown when sourced.",
    subcategories: ["pooled", "isolated", "rwa-credit"],
    attributes: [
      bool("lending", "Lending"),
      text("networks", "Networks (as published)"),
      text("lockup", "Lockup (as published)"),
    ],
    compareKeys: ["custody", "lending", "networks", "lockup", "feeSummary", "securitySummary"],
  },
  {
    id: "privacy",
    hub: "privacy",
    label: "Privacy tool",
    plural: "Privacy tools",
    group: "Tools",
    dedicated: false,
    summary: "Privacy wallets and mix-adjacent tools compared only on published mechanics and legal entity. TopPick does not help evade the law.",
    subcategories: ["wallet", "rpc", "shielded"],
    attributes: [
      text("networks", "Networks (as published)"),
      bool("open_source", "Open-source (if stated)"),
    ],
    compareKeys: ["custody", "networks", "open_source", "regulatorySummary", "securitySummary"],
  },
  {
    id: "gamefi",
    hub: "gamefi",
    label: "GameFi / web3 game",
    plural: "GameFi",
    group: "On-chain",
    dedicated: false,
    summary: "Third-party web3 games compared on custody of in-game assets and published markets. This is not the isolated TopPick games lab.",
    subcategories: ["game", "marketplace", "guild"],
    attributes: [
      bool("nft", "In-game NFTs (if stated)"),
      text("networks", "Networks (as published)"),
    ],
    compareKeys: ["custody", "networks", "nft", "productSummary"],
  },
  {
    id: "social",
    hub: "social",
    label: "Social / SocialFi",
    plural: "SocialFi",
    group: "On-chain",
    dedicated: false,
    summary: "Social tokens and SocialFi apps compared on who holds keys for the profile and published monetization. Follower counts are never fabricated.",
    subcategories: ["social", "token", "messaging"],
    attributes: [
      text("networks", "Networks (as published)"),
      bool("mobile_app", "Mobile app"),
    ],
    compareKeys: ["custody", "networks", "mobile_app", "productSummary"],
  },
  {
    id: "etf",
    hub: "etf",
    label: "Crypto ETF / ETP",
    plural: "Crypto ETFs",
    group: "Trading venues",
    dedicated: false,
    summary: "Spot and derivative crypto ETFs compared on issuer, custody of the underlying and published markets. This is not a brokerage order ticket.",
    subcategories: ["spot", "futures", "etp"],
    attributes: [
      text("kyc", "Broker access (as published)"),
    ],
    compareKeys: ["custody", "regulatorySummary", "kyc", "productSummary", "feeSummary"],
  },
  {
    id: "savings",
    hub: "savings",
    label: "Crypto savings / earn",
    plural: "Savings & earn",
    group: "Payments",
    dedicated: false,
    summary: "Earn and savings products compared on who holds the deposit, lockups and published yield source. APY is never estimated.",
    subcategories: ["flex", "locked", "dual"],
    attributes: [
      text("lockup", "Lockup (as published)"),
      bool("fiat", "Fiat earn (if stated)"),
      text("kyc", "KYC (as published)"),
    ],
    compareKeys: ["custody", "lockup", "fiat", "kyc", "feeSummary", "regulatorySummary"],
  },
  {
    id: "rpc",
    hub: "rpc",
    label: "RPC / node access",
    plural: "RPC providers",
    group: "Infrastructure",
    dedicated: false,
    summary: "RPC and node-access products compared on published networks, rate limits and who sees the requests. Latency numbers stay empty unless sourced.",
    subcategories: ["public", "private", "archive"],
    attributes: [
      bool("api", "API / RPC"),
      text("networks", "Networks (as published)"),
    ],
    compareKeys: ["networks", "api", "productSummary", "securitySummary"],
  },
  {
    id: "compliance",
    hub: "compliance",
    label: "Compliance / Travel Rule",
    plural: "Compliance tools",
    group: "Tools",
    dedicated: false,
    summary: "Travel Rule and compliance vendors compared on published checks and markets. This is not legal advice and not a KYC shortcut.",
    subcategories: ["travel-rule", "monitoring", "reporting"],
    attributes: [
      bool("api", "API"),
      text("kyc", "Checks (as published)"),
    ],
    compareKeys: ["kyc", "api", "regulatorySummary", "productSummary"],
  },
  {
    id: "index",
    hub: "indexes",
    label: "Crypto index / basket",
    plural: "Indexes",
    group: "Trading venues",
    dedicated: false,
    summary: "Index and basket products compared on methodology, custody of the constituents and published markets. Live index levels are never simulated.",
    subcategories: ["market-cap", "equal", "thematic"],
    attributes: [
      text("kyc", "Access (as published)"),
    ],
    compareKeys: ["custody", "kyc", "regulatorySummary", "feeSummary", "productSummary"],
  },
  {
    id: "structured",
    hub: "structured",
    label: "Structured product",
    plural: "Structured products",
    group: "Trading venues",
    dedicated: false,
    summary: "Dual, barrier and other structured notes compared on payoff as published and custody of the notional. Payoff diagrams are never invented.",
    subcategories: ["dual", "barrier", "note"],
    attributes: [
      text("lockup", "Tenor (as published)"),
      text("kyc", "Eligibility (as published)"),
    ],
    compareKeys: ["custody", "lockup", "kyc", "feeSummary", "regulatorySummary", "productSummary"],
  },
  {
    id: "otc",
    hub: "otc",
    label: "OTC desk",
    plural: "OTC desks",
    group: "Trading venues",
    dedicated: false,
    summary: "Over-the-counter desks compared on settlement, published minimums and who holds the inventory. Quoted spreads stay empty unless sourced.",
    subcategories: ["block", "rfq", "prime"],
    attributes: [
      text("kyc", "Eligibility (as published)"),
      bool("fiat", "Fiat settlement (if stated)"),
    ],
    compareKeys: ["custody", "kyc", "fiat", "feeSummary", "regulatorySummary"],
  },
  {
    id: "portfolio",
    hub: "portfolio",
    label: "Portfolio tracker",
    plural: "Portfolio trackers",
    group: "Tools",
    dedicated: false,
    summary: "Portfolio and tax-adjacent trackers compared on which venues they import and who can see the holdings. Balances are never simulated on TopPick.",
    subcategories: ["import", "manual", "tax-export"],
    attributes: [
      bool("api", "API / CSV import"),
      bool("mobile_app", "Mobile app"),
    ],
    compareKeys: ["api", "mobile_app", "productSummary", "securitySummary"],
  },
  {
    id: "bots",
    hub: "bots",
    label: "Trading bot",
    plural: "Trading bots",
    group: "Tools",
    dedicated: false,
    summary: "Grid, DCA and execution bots compared on where keys live and which venues they touch. Backtests and live PnL are never invented.",
    subcategories: ["grid", "dca", "execution"],
    attributes: [
      bool("api", "Exchange API"),
      text("kyc", "Venue access (as published)"),
    ],
    compareKeys: ["custody", "api", "kyc", "securitySummary", "productSummary"],
  },
  {
    id: "payroll",
    hub: "payroll",
    label: "Crypto payroll",
    plural: "Crypto payroll",
    group: "Payments",
    dedicated: false,
    summary: "Contractor and payroll rails compared on who holds float, supported assets and published markets. Tax treatment is never inferred.",
    subcategories: ["contractor", "payroll", "invoice"],
    attributes: [
      bool("fiat", "Fiat off-ramp (if stated)"),
      text("kyc", "KYC / KYB (as published)"),
    ],
    compareKeys: ["custody", "fiat", "kyc", "regulatorySummary", "feeSummary"],
  },
  {
    id: "vesting",
    hub: "vesting",
    label: "Token vesting",
    plural: "Vesting tools",
    group: "On-chain",
    dedicated: false,
    summary: "Vesting and unlock admin tools compared on who can change the schedule and which chains are published. Unlock charts are never drawn from guesswork.",
    subcategories: ["cliff", "linear", "admin"],
    attributes: [
      text("networks", "Networks (as published)"),
      bool("open_source", "Open-source (if stated)"),
    ],
    compareKeys: ["custody", "networks", "open_source", "productSummary"],
  },
  {
    id: "liquidity",
    hub: "liquidity",
    label: "Liquidity / market making",
    plural: "Liquidity desks",
    group: "On-chain",
    dedicated: false,
    summary: "Liquidity and market-making products compared on inventory custody and published venues. Depth charts stay empty unless sourced.",
    subcategories: ["amm", "otc-mm", "inventory"],
    attributes: [
      text("networks", "Networks / venues (as published)"),
      bool("api", "API"),
    ],
    compareKeys: ["custody", "networks", "api", "feeSummary", "productSummary"],
  },
  {
    id: "education",
    hub: "education",
    label: "Education platform",
    plural: "Education platforms",
    group: "Tools",
    dedicated: false,
    summary: "Third-party academies compared as products — custody of any linked account, published markets and whether a course is sold as advice. TopPick Learn stays separate.",
    subcategories: ["course", "academy", "cert"],
    attributes: [
      bool("mobile_app", "Mobile app"),
      text("kyc", "Paid access (as published)"),
    ],
    compareKeys: ["kyc", "mobile_app", "productSummary", "regulatorySummary"],
  },
  {
    id: "alerts",
    hub: "alerts",
    label: "Alert / watch tool",
    plural: "Alert tools",
    group: "Tools",
    dedicated: false,
    summary: "Price and on-chain alert tools compared on data source and who can see the watchlist. Live ticks are never fabricated on TopPick.",
    subcategories: ["price", "on-chain", "wallet-watch"],
    attributes: [
      bool("api", "API / webhooks"),
      bool("mobile_app", "Mobile app"),
    ],
    compareKeys: ["api", "mobile_app", "productSummary", "securitySummary"],
  },
];

export const VERIFICATION_STATES = ["needs_review", "imported", "manual", "verified", "stale", "missing"] as const;
export type VerificationState = (typeof VERIFICATION_STATES)[number];

export function isPlatformKind(value: string): value is PlatformKind {
  return (PLATFORM_KIND_IDS as readonly string[]).includes(value);
}

export function catalogById(id?: string | null) {
  return CATALOG.find((item) => item.id === id) || null;
}

export function catalogByHub(hub?: string | null) {
  return CATALOG.find((item) => item.hub === hub) || null;
}

export function platformPath(kind: string, slug?: string) {
  const cat = catalogById(kind);
  const hub = cat?.hub || `${kind}s`;
  return slug ? `/${hub}/${slug}` : `/${hub}`;
}

export function unknownLabel(value?: string | null) {
  const v = String(value || "").trim();
  return v || "Not disclosed";
}

export function classifyKindFromPublicText(input: { title?: string; description?: string; host?: string }) {
  const blob = `${input.title || ""} ${input.description || ""} ${input.host || ""}`.toLowerCase();
  const rules: Array<[PlatformKind, RegExp]> = [
    ["dex", /\b(dex|amm|uniswap|swap protocol|on-chain order)\b/],
    ["wallet", /\b(wallet|self-custod|hardware wallet|seed phrase|browser extension)\b/],
    ["crypto-card", /\b(crypto card|debit card|visa card|mastercard)\b/],
    ["onramp", /\b(on-?ramp|off-?ramp|buy crypto|sell crypto|moonpay)\b/],
    ["staking", /\b(liquid staking|staking protocol|earn yield)\b/],
    ["defi", /\b(defi|lending protocol|liquidity pool)\b/],
    ["broker", /\b(forex|cfd broker|mt4|mt5|spread betting)\b/],
    ["copy-trading", /\b(copy trad|social trad|mirror trad)\b/],
    ["trading-platform", /\b(trading terminal|tradingview)\b/],
    ["futures", /\b(perpetual|perps|crypto futures|dated futures)\b/],
    ["p2p", /\b(p2p|peer-to-peer|otc desk marketplace)\b/],
    ["nft", /\b(nft marketplace|nft exchange)\b/],
    ["launchpad", /\b(launchpad|ido|ieo|token sale)\b/],
    ["bridge", /\b(cross-chain bridge|token bridge)\b/],
    ["yield", /\b(yield aggregat|yield vault|auto-?compound)\b/],
    ["insurance", /\b(crypto insurance|protocol cover|smart contract cover)\b/],
    ["custody", /\b(qualified custod|institutional custod|prime custod)\b/],
    ["identity", /\b(kyc provider|identity verif|kyb provider)\b/],
    ["analytics", /\b(on-chain analytics|crypto analytics|nansen|dune)\b/],
    ["mining", /\b(mining pool|asic|hashrate)\b/],
    ["layer2", /\b(layer ?2|optimistic rollup|zk-?rollup)\b/],
    ["payments", /\b(crypto payment|merchant crypto|bitcoin payment)\b/],
    ["otc", /\b(otc desk|otc trading|block desk|rfq desk)\b/],
    ["institutional", /\b(prime broker|institutional crypto|prime services)\b/],
    ["dao", /\b(dao tool|governance portal|snapshot)\b/],
    ["oracle", /\b(price oracle|chainlink|data feed)\b/],
    ["validator", /\b(validator|node operator|staking-as-a-service)\b/],
    ["stablecoin", /\b(stablecoin|usdc issuer|usdt issuer)\b/],
    ["options", /\b(crypto options|options desk|vanilla options)\b/],
    ["restaking", /\b(restak|eigenlayer|shared security)\b/],
    ["rwa", /\b(real-world asset|tokenized treasury|rwa protocol)\b/],
    ["prediction", /\b(prediction market|event market|polymarket)\b/],
    ["lending", /\b(crypto lend|borrow market|money market protocol)\b/],
    ["privacy", /\b(privacy wallet|shielded pool|stealth address)\b/],
    ["gamefi", /\b(gamefi|web3 game|play-to-earn)\b/],
    ["social", /\b(socialfi|social token|farcaster)\b/],
    ["etf", /\b(bitcoin etf|crypto etf|spot etp)\b/],
    ["savings", /\b(crypto earn|savings account crypto|dual investment)\b/],
    ["rpc", /\b(rpc provider|node rpc|archive node)\b/],
    ["compliance", /\b(travel rule|crypto compliance|kyt provider)\b/],
    ["index", /\b(crypto index|index fund crypto|basket product)\b/],
    ["structured", /\b(dual investment|structured product|barrier note)\b/],
    ["portfolio", /\b(portfolio tracker|holdings tracker|portfolio app)\b/],
    ["bots", /\b(trading bot|grid bot|dca bot)\b/],
    ["payroll", /\b(crypto payroll|contractor crypto pay|crypto invoice pay)\b/],
    ["vesting", /\b(token vesting|vesting contract|token unlock schedule)\b/],
    ["liquidity", /\b(market making desk|liquidity provider desk|inventory desk)\b/],
    ["education", /\b(crypto education platform|trading academy|learn-to-earn course)\b/],
    ["alerts", /\b(price alert|whale alert|on-chain alert)\b/],
    ["explorer", /\b(block explorer|blockchain explorer|tx hash|etherscan)\b/],
    ["tax", /\b(crypto tax|tax software|capital gains report|accounting for crypto)\b/],
    ["tool", /\b(analytics dashboard|market data terminal|crypto utility)\b/],
    ["exchange", /\b(crypto exchange|spot trading|centralized exchange|cex)\b/],
  ];
  for (const [kind, pattern] of rules) {
    if (pattern.test(blob)) return { kind, confidence: "low" as const, status: "needs_review" as const };
  }
  return { kind: null, confidence: "low" as const, status: "needs_review" as const };
}
