export const PLATFORM_KIND_IDS = [
  "exchange",
  "dex",
  "broker",
  "trading-platform",
  "wallet",
  "defi",
  "staking",
  "crypto-card",
  "onramp",
  "tool",
  "explorer",
  "tax",
  "futures",
  "copy-trading",
  "p2p",
  "nft",
  "launchpad",
  "bridge",
  "yield",
  "insurance",
  "custody",
  "identity",
  "analytics",
  "mining",
  "layer2",
  "payments",
  "institutional",
  "dao",
  "oracle",
  "validator",
  "stablecoin",
] as const;

export type PlatformKind = (typeof PLATFORM_KIND_IDS)[number];

export type AttributeField = {
  key: string;
  label: string;
  type: "bool" | "text";
};

export type CatalogKind = {
  id: PlatformKind;
  hub: string;
  label: string;
  plural: string;
  group: string;
  dedicated: boolean;
  summary: string;
  subcategories: string[];
  attributes: AttributeField[];
  compareKeys: string[];
};

const bool = (key: string, label: string): AttributeField => ({ key, label, type: "bool" });
const text = (key: string, label: string): AttributeField => ({ key, label, type: "text" });

export const CATALOG: CatalogKind[] = [
  {
    id: "exchange",
    hub: "exchanges",
    label: "Centralized exchange",
    plural: "Exchanges",
    group: "Trading venues",
    dedicated: true,
    summary: "Custodial spot and derivatives venues researched by product scope, fees, funding, security context and market eligibility.",
    subcategories: ["spot", "derivatives", "hybrid"],
    attributes: [
      bool("spot", "Spot trading"),
      bool("margin", "Margin"),
      bool("futures", "Futures"),
      bool("options", "Options"),
      bool("staking", "Staking / earn"),
      bool("p2p", "P2P"),
      bool("fiat", "Fiat support"),
      bool("api", "Public API"),
      bool("tradingview", "TradingView integration"),
      bool("mobile_app", "Mobile app"),
      text("kyc", "KYC (as published)"),
    ],
    compareKeys: ["custody", "feeSummary", "spot", "futures", "margin", "staking", "fiat", "api", "mobile_app", "kyc"],
  },
  {
    id: "dex",
    hub: "dex",
    label: "Decentralized exchange",
    plural: "DEXs",
    group: "Trading venues",
    dedicated: false,
    summary: "Non-custodial swap and order-book protocols compared only on disclosed networks, custody model and published mechanics.",
    subcategories: ["amm", "order-book", "aggregator"],
    attributes: [
      bool("spot", "Spot / swap"),
      bool("perps", "Perpetuals"),
      bool("aggregator", "Aggregator"),
      text("networks", "Networks (as published)"),
      bool("open_source", "Open-source (if stated)"),
    ],
    compareKeys: ["custody", "networks", "spot", "perps", "open_source", "securitySummary"],
  },
  {
    id: "broker",
    hub: "brokers",
    label: "Broker",
    plural: "Brokers",
    group: "Trading venues",
    dedicated: true,
    summary: "Forex, CFD and multi-asset brokers reviewed by legal entity, instruments, cost disclosures and market access — not mixed with spot crypto venues.",
    subcategories: ["forex", "cfd", "multi-asset"],
    attributes: [
      bool("forex", "Forex"),
      bool("cfd", "CFDs"),
      bool("crypto_cfd", "Crypto CFDs"),
      bool("mt4", "MT4"),
      bool("mt5", "MT5"),
      text("kyc", "Onboarding (as published)"),
    ],
    compareKeys: ["feeSummary", "regulatorySummary", "forex", "cfd", "mt4", "mt5", "kyc"],
  },
  {
    id: "trading-platform",
    hub: "trading",
    label: "Trading platform",
    plural: "Trading platforms",
    group: "Trading venues",
    dedicated: false,
    summary: "Execution front-ends and multi-venue terminals compared by disclosed connectivity, instruments and custody relationship.",
    subcategories: ["terminal", "social", "copy"],
    attributes: [
      bool("spot", "Spot"),
      bool("futures", "Futures"),
      bool("api", "API"),
      bool("tradingview", "TradingView"),
      bool("mobile_app", "Mobile app"),
      bool("desktop_app", "Desktop app"),
    ],
    compareKeys: ["productSummary", "spot", "futures", "api", "mobile_app", "desktop_app"],
  },
  {
    id: "wallet",
    hub: "wallets",
    label: "Wallet",
    plural: "Wallets",
    group: "Custody",
    dedicated: true,
    summary: "Hardware, software, mobile and web wallets compared by custody, recovery, chain support and what the user actually controls.",
    subcategories: ["hardware", "software", "mobile", "browser", "custodial"],
    attributes: [
      bool("hardware", "Hardware device"),
      bool("mobile_app", "Mobile app"),
      bool("desktop_app", "Desktop app"),
      bool("browser_extension", "Browser extension"),
      bool("swap", "Built-in swap"),
      bool("staking", "Staking"),
      bool("nft", "NFT support"),
      bool("open_source", "Open-source (if stated)"),
      text("networks", "Networks (as published)"),
    ],
    compareKeys: ["custody", "hardware", "mobile_app", "browser_extension", "swap", "staking", "nft", "networks", "open_source"],
  },
  {
    id: "defi",
    hub: "defi",
    label: "DeFi platform",
    plural: "DeFi platforms",
    group: "On-chain",
    dedicated: false,
    summary: "On-chain apps researched from public documentation only. Yields and TVL are never invented.",
    subcategories: ["lending", "liquidity", "other"],
    attributes: [
      bool("lending", "Lending"),
      bool("swap", "Swap"),
      bool("staking", "Staking / lockups"),
      text("networks", "Networks (as published)"),
      bool("open_source", "Open-source (if stated)"),
    ],
    compareKeys: ["custody", "networks", "lending", "swap", "staking", "open_source"],
  },
  {
    id: "staking",
    hub: "staking",
    label: "Staking / earn",
    plural: "Staking & earn",
    group: "On-chain",
    dedicated: false,
    summary: "Earn and staking products compared on custody, lockups and disclosed terms. APY is only shown when a sourced figure exists.",
    subcategories: ["native", "liquid", "custodial-earn"],
    attributes: [
      bool("liquid_staking", "Liquid staking"),
      bool("custodial_earn", "Custodial earn"),
      text("lockup", "Lockup (as published)"),
      text("networks", "Networks (as published)"),
    ],
    compareKeys: ["custody", "liquid_staking", "custodial_earn", "lockup", "networks", "feeSummary"],
  },
  {
    id: "crypto-card",
    hub: "crypto-cards",
    label: "Crypto card",
    plural: "Crypto cards",
    group: "Payments",
    dedicated: false,
    summary: "Spend cards compared on issuer, custody of the underlying balance, fees and published market eligibility.",
    subcategories: ["debit", "credit"],
    attributes: [
      bool("fiat", "Fiat settlement"),
      text("networks", "Card network (as published)"),
      text("kyc", "KYC (as published)"),
    ],
    compareKeys: ["custody", "feeSummary", "fiat", "kyc", "regulatorySummary"],
  },
  {
    id: "onramp",
    hub: "on-ramps",
    label: "On/off-ramp",
    plural: "On/off-ramps",
    group: "Payments",
    dedicated: false,
    summary: "Fiat ramps compared on published payment rails, KYC and destination assets — never by guessed country coverage.",
    subcategories: ["on-ramp", "off-ramp", "both"],
    attributes: [
      bool("onramp", "Buy crypto"),
      bool("offramp", "Sell crypto"),
      text("rails", "Payment rails (as published)"),
      text("kyc", "KYC (as published)"),
    ],
    compareKeys: ["onramp", "offramp", "rails", "kyc", "feeSummary"],
  },
  {
    id: "tool",
    hub: "tools",
    label: "Trading / analytics tool",
    plural: "Tools",
    group: "Tools",
    dedicated: false,
    summary: "Bots, trackers and data tools compared on disclosed features. Market prices are never simulated here.",
    subcategories: ["bot", "portfolio", "analytics", "security"],
    attributes: [
      bool("bot", "Automation / bot"),
      bool("portfolio", "Portfolio tracking"),
      bool("analytics", "Analytics / data"),
      bool("api", "API"),
      bool("mobile_app", "Mobile app"),
    ],
    compareKeys: ["bot", "portfolio", "analytics", "api", "mobile_app", "productSummary"],
  },
  {
    id: "explorer",
    hub: "explorers",
    label: "Blockchain explorer",
    plural: "Explorers",
    group: "Infrastructure",
    dedicated: false,
    summary: "Block explorers and chain browsers compared on disclosed networks, APIs and what they actually index — never simulated chain data.",
    subcategories: ["l1", "l2", "multi-chain"],
    attributes: [
      bool("api", "Public API"),
      text("networks", "Networks (as published)"),
      bool("analytics", "Analytics views"),
    ],
    compareKeys: ["networks", "api", "analytics", "productSummary"],
  },
  {
    id: "tax",
    hub: "tax",
    label: "Crypto tax / accounting",
    plural: "Tax & accounting",
    group: "Tools",
    dedicated: false,
    summary: "Tax and accounting products compared on published jurisdictions, import methods and reporting scope. This is not tax advice.",
    subcategories: ["tax", "accounting", "bookkeeping"],
    attributes: [
      bool("api", "API / CSV import"),
      text("kyc", "Account requirements (as published)"),
      bool("mobile_app", "Mobile app"),
    ],
    compareKeys: ["kyc", "api", "mobile_app", "productSummary", "regulatorySummary"],
  },
  {
    id: "futures",
    hub: "futures",
    label: "Perpetuals / futures venue",
    plural: "Futures & perps",
    group: "Trading venues",
    dedicated: false,
    summary: "Perpetual and dated futures venues compared on custody, published contract specs and market access. Funding rates are never invented.",
    subcategories: ["perps", "dated", "options"],
    attributes: [
      bool("futures", "Dated futures"),
      bool("perps", "Perpetuals"),
      bool("options", "Options"),
      bool("api", "Public API"),
      text("kyc", "KYC (as published)"),
    ],
    compareKeys: ["custody", "futures", "perps", "options", "api", "feeSummary", "kyc"],
  },
  {
    id: "copy-trading",
    hub: "copy-trading",
    label: "Copy / social trading",
    plural: "Copy trading",
    group: "Trading venues",
    dedicated: false,
    summary: "Copy and social trading products compared on who you follow, custody of the copied account, and published fees. Past results are never shown as forecasts.",
    subcategories: ["copy", "social", "signals"],
    attributes: [
      bool("mobile_app", "Mobile app"),
      bool("api", "API / signals"),
      text("kyc", "Onboarding (as published)"),
    ],
    compareKeys: ["custody", "feeSummary", "mobile_app", "kyc", "productSummary"],
  },
  {
    id: "p2p",
    hub: "p2p",
    label: "P2P marketplace",
    plural: "P2P markets",
    group: "Payments",
    dedicated: false,
    summary: "Peer-to-peer crypto marketplaces compared on escrow, payment rails and published dispute process. Escrow is not the same as exchange custody.",
    subcategories: ["escrow", "otc"],
    attributes: [
      bool("fiat", "Fiat rails"),
      text("kyc", "KYC (as published)"),
      text("rails", "Payment methods (as published)"),
    ],
    compareKeys: ["custody", "fiat", "rails", "kyc", "feeSummary"],
  },
  {
    id: "nft",
    hub: "nft",
    label: "NFT marketplace",
    plural: "NFT markets",
    group: "On-chain",
    dedicated: false,
    summary: "NFT marketplaces compared on custody of the item, fees and published networks. Floor prices and volume are never fabricated.",
    subcategories: ["marketplace", "aggregator"],
    attributes: [
      bool("nft", "NFT trading"),
      text("networks", "Networks (as published)"),
      bool("open_source", "Open-source (if stated)"),
    ],
    compareKeys: ["custody", "networks", "feeSummary", "nft", "open_source"],
  },
  {
    id: "launchpad",
    hub: "launchpads",
    label: "Launchpad / token sale",
    plural: "Launchpads",
    group: "On-chain",
    dedicated: false,
    summary: "Token sale and launchpad products compared on eligibility, custody of committed funds and published terms. Allocations are never invented.",
    subcategories: ["ido", "ieo", "launchpad"],
    attributes: [
      text("kyc", "Eligibility (as published)"),
      bool("staking", "Stake-to-join (if stated)"),
      text("networks", "Networks (as published)"),
    ],
    compareKeys: ["custody", "kyc", "staking", "networks", "productSummary"],
  },
  {
    id: "bridge",
    hub: "bridges",
    label: "Cross-chain bridge",
    plural: "Bridges",
    group: "Infrastructure",
    dedicated: false,
    summary: "Bridges compared on published chains, custody of in-flight assets and documented failure modes. TVL and speed claims stay empty unless sourced.",
    subcategories: ["lock-mint", "liquidity", "canonical"],
    attributes: [
      text("networks", "Networks (as published)"),
      bool("open_source", "Open-source (if stated)"),
    ],
    compareKeys: ["custody", "networks", "open_source", "securitySummary", "feeSummary"],
  },
  {
    id: "yield",
    hub: "yield",
    label: "Yield aggregator",
    plural: "Yield aggregators",
    group: "On-chain",
    dedicated: false,
    summary: "Yield routers compared on custody of deposits, published strategies and lockups. APY is shown only when a sourced figure exists.",
    subcategories: ["vault", "auto-compound"],
    attributes: [
      bool("lending", "Lending routes"),
      bool("staking", "Staking routes"),
      text("networks", "Networks (as published)"),
      text("lockup", "Lockup (as published)"),
    ],
    compareKeys: ["custody", "networks", "lending", "staking", "lockup", "feeSummary"],
  },
  {
    id: "insurance",
    hub: "insurance",
    label: "Crypto insurance / cover",
    plural: "Insurance & cover",
    group: "Security",
    dedicated: false,
    summary: "On-chain and commercial cover products compared on what is actually insured, who pays claims and published exclusions. Cover is not a guarantee.",
    subcategories: ["protocol", "custodial", "wallet"],
    attributes: [
      text("kyc", "Eligibility (as published)"),
      bool("open_source", "Open-source (if stated)"),
    ],
    compareKeys: ["productSummary", "kyc", "regulatorySummary", "securitySummary"],
  },
  {
    id: "custody",
    hub: "custody",
    label: "Institutional custody",
    plural: "Custody providers",
    group: "Custody",
    dedicated: false,
    summary: "Qualified and institutional custodians compared on who holds keys, bankruptcy remoteness as published, and market eligibility. This is not legal advice.",
    subcategories: ["qualified", "prime", "segregated"],
    attributes: [
      bool("api", "API / settlement"),
      text("kyc", "Onboarding (as published)"),
    ],
    compareKeys: ["custody", "regulatorySummary", "securitySummary", "kyc", "api"],
  },
  {
    id: "identity",
    hub: "identity",
    label: "Identity / KYC provider",
    plural: "Identity & KYC",
    group: "Tools",
    dedicated: false,
    summary: "KYC and identity vendors compared on published checks and data handling. TopPick does not score how “easy” onboarding feels.",
    subcategories: ["kyc", "kyb", "attestation"],
    attributes: [
      bool("api", "API"),
      text("kyc", "Checks (as published)"),
    ],
    compareKeys: ["kyc", "api", "regulatorySummary", "productSummary"],
  },
  {
    id: "analytics",
    hub: "analytics",
    label: "On-chain analytics",
    plural: "Analytics desks",
    group: "Tools",
    dedicated: false,
    summary: "Analytics and data desks compared on disclosed sources and networks. Charts here never pretend to be a live market feed.",
    subcategories: ["on-chain", "portfolio", "terminal"],
    attributes: [
      bool("analytics", "Analytics views"),
      bool("api", "API"),
      bool("mobile_app", "Mobile app"),
      text("networks", "Networks (as published)"),
    ],
    compareKeys: ["analytics", "api", "networks", "mobile_app", "productSummary"],
  },
  {
    id: "mining",
    hub: "mining",
    label: "Mining pool / hardware",
    plural: "Mining",
    group: "Infrastructure",
    dedicated: false,
    summary: "Pools and mining products compared on payout method, custody of rewards and published fees. Hashprice is never invented.",
    subcategories: ["pool", "hardware", "cloud"],
    attributes: [
      bool("api", "API / stats"),
      text("networks", "Coins / networks (as published)"),
    ],
    compareKeys: ["feeSummary", "networks", "api", "productSummary"],
  },
  {
    id: "layer2",
    hub: "layer2",
    label: "Layer 2 / scaling",
    plural: "Layer 2",
    group: "Infrastructure",
    dedicated: false,
    summary: "L2 and scaling networks compared on published security model, bridges and documented operators. Throughput numbers stay empty unless sourced.",
    subcategories: ["rollup", "sidechain", "validium"],
    attributes: [
      text("networks", "Base / stack (as published)"),
      bool("open_source", "Open-source (if stated)"),
    ],
    compareKeys: ["networks", "open_source", "securitySummary", "productSummary"],
  },
  {
    id: "payments",
    hub: "payments",
    label: "Crypto payments",
    plural: "Crypto payments",
    group: "Payments",
    dedicated: false,
    summary: "Merchant and payout rails compared on settlement asset, custody of float and published markets. Processing volume is never fabricated.",
    subcategories: ["merchant", "payout", "invoice"],
    attributes: [
      bool("fiat", "Fiat settlement"),
      text("kyc", "Merchant KYC (as published)"),
      bool("api", "API"),
    ],
    compareKeys: ["custody", "fiat", "kyc", "api", "feeSummary"],
  },
  {
    id: "institutional",
    hub: "institutional",
    label: "Prime / institutional desk",
    plural: "Institutional desks",
    group: "Trading venues",
    dedicated: false,
    summary: "Prime brokerage and OTC desks compared on published counterparties, custody and onboarding. Quotes and inventory are never invented.",
    subcategories: ["prime", "otc", "credit"],
    attributes: [
      bool("api", "FIX / API"),
      text("kyc", "Onboarding (as published)"),
    ],
    compareKeys: ["custody", "regulatorySummary", "kyc", "api", "productSummary"],
  },
  {
    id: "dao",
    hub: "dao",
    label: "DAO tooling",
    plural: "DAO tools",
    group: "On-chain",
    dedicated: false,
    summary: "Governance and DAO tools compared on voting custody, treasuries and published networks. Token prices are not shown as performance.",
    subcategories: ["governance", "treasury", "multisig"],
    attributes: [
      text("networks", "Networks (as published)"),
      bool("open_source", "Open-source (if stated)"),
    ],
    compareKeys: ["custody", "networks", "open_source", "productSummary"],
  },
  {
    id: "oracle",
    hub: "oracles",
    label: "Oracle / data feed",
    plural: "Oracles",
    group: "Infrastructure",
    dedicated: false,
    summary: "Oracle networks compared on published feeds, update model and documented operators. Live prices are never simulated on TopPick.",
    subcategories: ["price", "vrf", "automation"],
    attributes: [
      text("networks", "Networks (as published)"),
      bool("open_source", "Open-source (if stated)"),
      bool("api", "API / feeds"),
    ],
    compareKeys: ["networks", "api", "open_source", "securitySummary"],
  },
  {
    id: "validator",
    hub: "validators",
    label: "Validator / node operator",
    plural: "Validators",
    group: "Infrastructure",
    dedicated: false,
    summary: "Validators and node operators compared on published networks, slashing treatment and custody of staked assets. APR is only shown when sourced.",
    subcategories: ["validator", "rpc", "node"],
    attributes: [
      text("networks", "Networks (as published)"),
      text("lockup", "Bond / lockup (as published)"),
    ],
    compareKeys: ["custody", "networks", "lockup", "feeSummary", "securitySummary"],
  },
  {
    id: "stablecoin",
    hub: "stablecoins",
    label: "Stablecoin issuer",
    plural: "Stablecoins",
    group: "Payments",
    dedicated: false,
    summary: "Stablecoin issuers compared on reserve disclosures, redemption and published markets. Peg strength is never scored from a chart we do not source.",
    subcategories: ["fiat-backed", "crypto-backed", "algorithmic"],
    attributes: [
      bool("fiat", "Fiat redemption (if stated)"),
      text("networks", "Networks (as published)"),
    ],
    compareKeys: ["regulatorySummary", "fiat", "networks", "productSummary", "securitySummary"],
  },
];

export const VERIFICATION_STATES = ["needs_review", "imported", "manual", "verified", "stale", "missing"] as const;
export type VerificationState = (typeof VERIFICATION_STATES)[number];

export function isPlatformKind(value: string): value is PlatformKind {
  return (PLATFORM_KIND_IDS as readonly string[]).includes(value);
}

export function catalogById(id?: string | null) {
  return CATALOG.find((item) => item.id === id) || null;
}

export function catalogByHub(hub?: string | null) {
  return CATALOG.find((item) => item.hub === hub) || null;
}

export function platformPath(kind: string, slug?: string) {
  const cat = catalogById(kind);
  const hub = cat?.hub || `${kind}s`;
  return slug ? `/${hub}/${slug}` : `/${hub}`;
}

export function unknownLabel(value?: string | null) {
  const v = String(value || "").trim();
  return v || "Not disclosed";
}

export function classifyKindFromPublicText(input: { title?: string; description?: string; host?: string }) {
  const blob = `${input.title || ""} ${input.description || ""} ${input.host || ""}`.toLowerCase();
  const rules: Array<[PlatformKind, RegExp]> = [
    ["dex", /\b(dex|amm|uniswap|swap protocol|on-chain order)\b/],
    ["wallet", /\b(wallet|self-custod|hardware wallet|seed phrase|browser extension)\b/],
    ["crypto-card", /\b(crypto card|debit card|visa card|mastercard)\b/],
    ["onramp", /\b(on-?ramp|off-?ramp|buy crypto|sell crypto|moonpay)\b/],
    ["staking", /\b(liquid staking|staking protocol|earn yield)\b/],
    ["defi", /\b(defi|lending protocol|liquidity pool)\b/],
    ["broker", /\b(forex|cfd broker|mt4|mt5|spread betting)\b/],
    ["copy-trading", /\b(copy trad|social trad|mirror trad)\b/],
    ["trading-platform", /\b(trading terminal|tradingview)\b/],
    ["futures", /\b(perpetual|perps|crypto futures|dated futures)\b/],
    ["p2p", /\b(p2p|peer-to-peer|otc desk marketplace)\b/],
    ["nft", /\b(nft marketplace|nft exchange)\b/],
    ["launchpad", /\b(launchpad|ido|ieo|token sale)\b/],
    ["bridge", /\b(cross-chain bridge|token bridge)\b/],
    ["yield", /\b(yield aggregat|yield vault|auto-?compound)\b/],
    ["insurance", /\b(crypto insurance|protocol cover|smart contract cover)\b/],
    ["custody", /\b(qualified custod|institutional custod|prime custod)\b/],
    ["identity", /\b(kyc provider|identity verif|kyb provider)\b/],
    ["analytics", /\b(on-chain analytics|crypto analytics|nansen|dune)\b/],
    ["mining", /\b(mining pool|asic|hashrate)\b/],
    ["layer2", /\b(layer ?2|optimistic rollup|zk-?rollup)\b/],
    ["payments", /\b(crypto payment|merchant crypto|bitcoin payment)\b/],
    ["institutional", /\b(prime broker|otc desk|institutional crypto)\b/],
    ["dao", /\b(dao tool|governance portal|snapshot)\b/],
    ["oracle", /\b(price oracle|chainlink|data feed)\b/],
    ["validator", /\b(validator|node operator|staking-as-a-service)\b/],
    ["stablecoin", /\b(stablecoin|usdc issuer|usdt issuer)\b/],
    ["explorer", /\b(block explorer|blockchain explorer|tx hash|etherscan)\b/],
    ["tax", /\b(crypto tax|tax software|capital gains report|accounting for crypto)\b/],
    ["tool", /\b(portfolio tracker|trading bot|analytics dashboard|market data)\b/],
    ["exchange", /\b(crypto exchange|spot trading|centralized exchange|cex)\b/],
  ];
  for (const [kind, pattern] of rules) {
    if (pattern.test(blob)) return { kind, confidence: "low" as const, status: "needs_review" as const };
  }
  return { kind: null, confidence: "low" as const, status: "needs_review" as const };
}
