import type { Guide, Platform } from "./types";

// Seed content is intentionally conservative. Verify current fees, licensing, market availability
// and affiliate eligibility before turning any platform CTA live.
export const platforms: Platform[] = [
  { id:"binance", slug:"binance", name:"Binance", kind:"exchange", logoText:"BN", short:"Global crypto exchange", description:"A major cryptocurrency trading platform. Market availability, products and onboarding rules vary by jurisdiction.", website:"https://www.binance.com", status:"research", featured:true, tags:["spot","advanced trading","app"], markets:["Market review required"], custody:"custodial", productNote:"Research current local entity, fees, products and promotion permissions before publishing.", updatedAt:"2026-08-20" },
  { id:"kraken", slug:"kraken", name:"Kraken", kind:"exchange", logoText:"KR", short:"Crypto exchange & trading platform", description:"A cryptocurrency platform offering exchange and trading services in supported markets.", website:"https://www.kraken.com", status:"research", featured:true, tags:["spot","pro tools","security"], markets:["Market review required"], custody:"custodial", productNote:"Verify jurisdiction-specific availability and current pricing from official sources.", updatedAt:"2026-08-20" },
  { id:"coinbase", slug:"coinbase", name:"Coinbase", kind:"exchange", logoText:"CB", short:"Crypto exchange & app", description:"A cryptocurrency platform focused on buying, selling, holding and related services where available.", website:"https://www.coinbase.com", status:"research", featured:true, tags:["beginner","app","spot"], markets:["Market review required"], custody:"custodial", productNote:"Confirm current product scope, local entity and affiliate terms before promotion.", updatedAt:"2026-08-20" },
  { id:"gate-io", slug:"gate-io", name:"Gate.io", kind:"exchange", logoText:"GT", short:"Crypto exchange", description:"A digital-asset trading platform with product availability that can differ significantly by location.", website:"https://www.gate.io", status:"research", tags:["spot","advanced trading"], markets:["Market review required"], custody:"custodial", productNote:"Treat GEO eligibility as fail-closed until verified.", updatedAt:"2026-08-20" },
  { id:"xm", slug:"xm", name:"XM", kind:"broker", logoText:"XM", short:"Online broker", description:"An online trading brand whose instruments, legal entities and promotion rules depend on the user’s jurisdiction.", website:"https://www.xm.com", status:"research", featured:true, tags:["forex","CFDs","MT4/MT5"], markets:["Market review required"], custody:null, productNote:"Broker marketing is regulated financial promotion. Verify entity, instrument availability and local rules first.", updatedAt:"2026-08-20" },
  { id:"etoro", slug:"etoro", name:"eToro", kind:"broker", logoText:"ET", short:"Multi-asset trading platform", description:"A multi-asset platform with jurisdiction-specific products, entities and risk disclosures.", website:"https://www.etoro.com", status:"research", tags:["multi-asset","app","social"], markets:["Market review required"], custody:"mixed", productNote:"Do not reuse one market’s product claims or risk warnings in another.", updatedAt:"2026-08-20" },
  { id:"ledger", slug:"ledger", name:"Ledger", kind:"wallet", logoText:"LG", short:"Hardware wallet ecosystem", description:"A hardware-wallet ecosystem used for self-custody of supported digital assets.", website:"https://www.ledger.com", status:"research", featured:true, tags:["hardware","cold storage","self-custody"], markets:["Product availability review required"], custody:"non-custodial", productNote:"Verify device, software and regional shipping details before commercial promotion.", updatedAt:"2026-08-20" },
  { id:"trezor", slug:"trezor", name:"Trezor", kind:"wallet", logoText:"TZ", short:"Hardware wallet", description:"A hardware-wallet product line designed for self-custody of supported digital assets.", website:"https://trezor.io", status:"research", tags:["hardware","cold storage","self-custody"], markets:["Product availability review required"], custody:"non-custodial", productNote:"Confirm current models, supported assets and regional purchase terms from official sources.", updatedAt:"2026-08-20" }
];

export const guides: Guide[] = [
  { slug:"how-to-choose-a-crypto-exchange", title:"How to choose a crypto exchange", excerpt:"A practical framework for comparing security, fees, funding, product access and jurisdiction.", category:"exchanges", readTime:"8 min" },
  { slug:"exchange-vs-wallet", title:"Crypto exchange vs wallet", excerpt:"Understand custody, control of private keys, convenience and the different risk profiles.", category:"wallets", readTime:"7 min" },
  { slug:"broker-vs-exchange", title:"Broker vs crypto exchange", excerpt:"The structural differences between trading through a broker and trading on a digital-asset exchange.", category:"brokers", readTime:"9 min" },
  { slug:"crypto-fees-explained", title:"Crypto fees explained", excerpt:"Maker/taker fees, spreads, funding charges and withdrawals — what to compare before signing up.", category:"learn", readTime:"10 min" },
  { slug:"self-custody-basics", title:"Self-custody basics", excerpt:"Seed phrases, hot vs cold wallets and practical security habits for beginners.", category:"wallets", readTime:"11 min" },
  { slug:"how-we-rate-platforms", title:"How our platform scoring works", excerpt:"A transparent evidence-first methodology for exchanges, brokers and wallets.", category:"learn", readTime:"6 min" }
];

export const getPlatform = (slug: string) => platforms.find(p => p.slug === slug);
