export const RESEARCH_JOBS = [
  { href: "/exchanges", title: "Buy or sell on a venue", copy: "Custodial spot and derivatives venues. Compare entity, custody and fees — not a homepage slogan." },
  { href: "/wallets", title: "Hold keys yourself", copy: "Hardware, software and mobile wallets. Recovery design matters more than a bonus." },
  { href: "/brokers", title: "Use a broker", copy: "Forex, CFD and multi-asset. Ownership of the underlying asset is often not the product." },
  { href: "/futures", title: "Trade perps or futures", copy: "Dated futures and perpetuals. Funding and liquidation stay empty unless sourced." },
  { href: "/options", title: "Use options", copy: "Premium, expiry and collateral. Greeks are never simulated." },
  { href: "/copy-trading", title: "Copy another account", copy: "Mirroring is still a custody and cost product. Past results are not a forecast." },
  { href: "/dex", title: "Swap on-chain", copy: "AMMs and order-book DEXs. Smart-contract risk replaces venue-custody risk." },
  { href: "/bridges", title: "Move value across chains", copy: "While funds are in flight the custody model is often neither a wallet nor an exchange." },
  { href: "/on-ramps", title: "Convert fiat", copy: "On-ramps and off-ramps. Country coverage is operator-specific." },
  { href: "/crypto-cards", title: "Spend from a card", copy: "Crypto cards compared on custody of float, fees as published, and market eligibility." },
  { href: "/staking", title: "Stake", copy: "Lockups, receipt tokens and slashing — only when the operator publishes them." },
  { href: "/restaking", title: "Restake", copy: "Extra slashing conditions. Points are not yield." },
  { href: "/lending", title: "Lend or borrow", copy: "Collateral, liquidation and who holds the asset. APR is never invented." },
  { href: "/savings", title: "Park funds in earn", copy: "Operator savings books. APY stays empty unless sourced." },
  { href: "/tax", title: "Report activity", copy: "Tax and accounting tools compared on supported venues and export methods." },
  { href: "/custody", title: "Use institutional custody", copy: "Qualified custodians. Bankruptcy remoteness only as published." },
  { href: "/rwa", title: "Hold a tokenized asset", copy: "The legal wrapper and the off-chain custodian are the product." },
  { href: "/prediction", title: "Price an event", copy: "Prediction markets. Odds are not a live tape on TopPick." },
  { href: "/etf", title: "Use a listed crypto ETF", copy: "Issuer, custody of the underlying, and the market where the share trades." },
  { href: "/rpc", title: "Connect an app to a chain", copy: "RPC providers compared on published networks and who sees the requests." },
  { href: "/compliance", title: "Travel Rule / compliance", copy: "Vendors compared on published checks. This is not legal advice." },
  { href: "/indexes", title: "Hold a basket / index", copy: "Methodology and custody of the constituents. Live levels are never simulated." },
  { href: "/structured", title: "Use a structured note", copy: "Payoff as published. Diagrams are never invented." },
  { href: "/markets", title: "Check your country first", copy: "Availability and promotional eligibility are stored separately." },
] as const;
