/** Public, indexable routes that must exist as pages or catalog hubs. */
export const PUBLIC_STATIC_PATHS = [
  "/",
  "/about",
  "/apps",
  "/finder",
  "/glossary",
  "/source-policy",
  "/partners",
  "/exchanges",
  "/brokers",
  "/wallets",
  "/research",
  "/updates",
  "/compare",
  "/learn",
  "/markets",
  "/fees",
  "/security",
  "/how-we-rate",
  "/editorial-policy",
  "/corrections",
  "/contact",
  "/opportunities",
  "/rewards",
  "/niches",
  "/start",
  "/jobs",
  "/faq",
  "/legal/affiliate-disclosure",
  "/legal/risk-disclosure",
  "/legal/privacy",
  "/legal/cookies",
  "/legal/terms",
] as const;

export const INTENTIONAL_NOINDEX_PATHS = [
  "/admin",
  "/admin/login",
  "/account",
  "/partner",
  "/partners/apply",
  "/search",
  "/unavailable",
  "/games",
] as const;

export const FOOTER_PATHS = [
  "/exchanges",
  "/brokers",
  "/wallets",
  "/dex",
  "/niches",
  "/jobs",
  "/start",
  "/faq",
  "/finder",
  "/compare",
  "/search",
  "/learn",
  "/glossary",
  "/opportunities",
  "/account",
  "/apps",
  "/markets",
  "/how-we-rate",
  "/partners",
  "/editorial-policy",
  "/source-policy",
  "/corrections",
  "/contact",
  "/legal/affiliate-disclosure",
  "/legal/risk-disclosure",
  "/legal/privacy",
  "/legal/terms",
  "/research",
  "/security",
] as const;
