import type { Metadata } from "next";
import type { Platform } from "@/lib/types";
import { SITE_NAME, SITE_URL } from "./site";
type SeoInput={title?:string|null;description?:string|null;path?:string;ogImage?:string|null;noIndex?:boolean;type?:"website"|"article";keywords?:string[]};
const clean=(v:string)=>v.replace(/\s+/g," ").trim();
const clamp=(v:string,m:number)=>v.length<=m?v:`${v.slice(0,m-1).trimEnd()}…`;
const DEFAULT_DESCRIPTION="Independent comparisons of brokers, crypto exchanges, wallets and trading platforms, with fees, security, product access and market context.";
function normalizeDescription(value?:string|null){const base=clean(value||DEFAULT_DESCRIPTION);return clamp(base.length>=110?base:`${base} Availability and partner promotions can vary by jurisdiction.`,160)}
export function buildMetadata(input:SeoInput):Metadata{const raw=input.title||`${SITE_NAME} — Compare Brokers, Exchanges & Wallets`;const title=clamp(clean(raw),64);const description=normalizeDescription(input.description);const path=input.path||"/";const url=new URL(path,SITE_URL).toString();const ogImage=input.ogImage||`${SITE_URL}/og-default.svg`;return{title,description,keywords:input.keywords,metadataBase:new URL(SITE_URL),alternates:{canonical:url},openGraph:{title,description,url,siteName:SITE_NAME,type:input.type||"website",images:[{url:ogImage,width:1200,height:630,alt:title}]},twitter:{card:"summary_large_image",title,description,images:[ogImage]},robots:input.noIndex?{index:false,follow:true,googleBot:{index:false,follow:true}}:{index:true,follow:true,googleBot:{index:true,follow:true,"max-image-preview":"large","max-snippet":-1,"max-video-preview":-1}}}}
export function organizationJsonLd(){return{"@context":"https://schema.org","@type":"Organization","@id":`${SITE_URL}/#organization`,name:SITE_NAME,url:SITE_URL,logo:{"@type":"ImageObject",url:`${SITE_URL}/icon.svg`}}}
export function websiteJsonLd(){return{"@context":"https://schema.org","@type":"WebSite","@id":`${SITE_URL}/#website`,name:SITE_NAME,url:SITE_URL,publisher:{"@id":`${SITE_URL}/#organization`},potentialAction:{"@type":"SearchAction",target:`${SITE_URL}/search?q={search_term_string}`,"query-input":"required name=search_term_string"}}}
export function webPageJsonLd(input:{name:string;description:string;path:string}){return{"@context":"https://schema.org","@type":"WebPage",name:input.name,description:input.description,url:new URL(input.path,SITE_URL).toString(),isPartOf:{"@id":`${SITE_URL}/#website`},publisher:{"@id":`${SITE_URL}/#organization`}}}
export function breadcrumbJsonLd(items:{name:string;url:string}[]){return{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:items.map((item,i)=>({"@type":"ListItem",position:i+1,name:item.name,item:item.url}))}}
export function itemListJsonLd(items:{name:string;url:string}[]){return{"@context":"https://schema.org","@type":"ItemList",numberOfItems:items.length,itemListElement:items.map((item,i)=>({"@type":"ListItem",position:i+1,name:item.name,url:item.url}))}}
export function faqJsonLd(items:{question:string;answer:string}[]){return{"@context":"https://schema.org","@type":"FAQPage",mainEntity:items.map(item=>({"@type":"Question",name:item.question,acceptedAnswer:{"@type":"Answer",text:item.answer}}))}}
export function reviewJsonLd(platform:Platform,path:string){return{"@context":"https://schema.org","@type":"Review",itemReviewed:{"@type":"Organization",name:platform.name,url:platform.website!=="#"?platform.website:undefined},author:{"@id":`${SITE_URL}/#organization`},publisher:{"@id":`${SITE_URL}/#organization`},url:`${SITE_URL}${path}`,reviewBody:platform.short}}
