export type { PlatformKind } from "./catalog";
export type PlatformStatus = "research" | "verified" | "restricted";
export type VerificationState = "needs_review" | "imported" | "manual" | "verified" | "stale" | "missing";
export type Platform = {
  id?: string;
  slug: string;
  name: string;
  short: string;
  description: string;
  kind: import("./catalog").PlatformKind;
  status: PlatformStatus;
  logoText: string;
  logoUrl?: string | null;
  tags: string[];
  updatedAt: string;
  website: string;
  affiliateUrl?: string | null;
  custody?: string | null;
  markets: string[];
  productNote: string;
  feeSummary?: string | null;
  securitySummary?: string | null;
  regulatorySummary?: string | null;
  productSummary?: string | null;
  pros?: string[];
  cons?: string[];
  featured?: boolean;
  visible?: boolean;
  seoTitle?: string | null;
  seoDescription?: string | null;
  subcategory?: string | null;
  attributes?: Record<string, string | boolean | null>;
  verificationStatus?: VerificationState;
  lastVerifiedAt?: string | null;
  operatorName?: string | null;
  foundedYear?: number | null;
  editorialScore?: number | null;
  archived?: boolean;
  coverUrl?: string | null;
  languages?: string[];
  screenshots?: string[];
  ctaLabel?: string | null;
  riskNotes?: string | null;
};
export type Guide = { slug: string; title: string; excerpt: string; category: "exchanges" | "brokers" | "wallets" | "learn"; readTime: string };
