"use client";
import { useActionState } from "react";
import { useRouter } from "next/navigation";
import { saveBonus, deleteBonus } from "@/lib/actions/admin";

type Any=Record<string,any>;
const input:React.CSSProperties={width:"100%",boxSizing:"border-box",padding:"10px 12px",borderRadius:11,border:"1px solid rgba(255,255,255,.1)",background:"#0c1119",color:"#fff"};
const label:React.CSSProperties={display:"block",fontSize:11,fontWeight:800,color:"#94a3b8",textTransform:"uppercase",letterSpacing:".05em",marginBottom:6};
function F({n,t,v,p,type="text"}:any){return <label><span style={label}>{t}</span><input style={input} name={n} type={type} defaultValue={v??""} placeholder={p}/></label>}
export function BonusForm({bonus,casinos}:{bonus?:Any,casinos:{id:string,name:string}[]}){
 const router=useRouter(); const [state,action,pending]=useActionState(async(_:any,fd:FormData)=>{const r=await saveBonus(fd);if(r.success){router.push("/admin/bonuses");router.refresh()}return r},{} as any);
 return <div style={{position:"fixed",inset:0,zIndex:99999,background:"rgba(0,0,0,.82)",display:"grid",placeItems:"center",padding:16}}><div style={{width:"min(760px,100%)",maxHeight:"94vh",overflow:"auto",background:"#0b1017",border:"1px solid rgba(255,255,255,.1)",borderRadius:20,padding:22}}>
 <div style={{display:"flex",justifyContent:"space-between",marginBottom:20}}><div><b style={{fontSize:20,color:"#fff"}}>{bonus?.id?"Edit Bonus":"Add Bonus"}</b><div style={{color:"#7f8b9c",fontSize:13,marginTop:4}}>Fast manual bonus entry. Add only the terms players actually need.</div></div><button onClick={()=>router.push("/admin/bonuses")} style={{background:"none",border:0,color:"#fff",fontSize:24}}>×</button></div>
 <form action={action} style={{display:"grid",gap:15}}>{bonus?.id&&<input type="hidden" name="id" value={bonus.id}/>}<input type="hidden" name="slug" value={bonus?.slug??""}/>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:13}}>
 <label><span style={label}>Casino *</span><select style={input} name="casino_id" defaultValue={bonus?.casino_id??""} required><option value="">Choose casino</option>{casinos.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
 <F n="title" t="Bonus title *" v={bonus?.title} p="100% up to €500 + 100 FS"/><label><span style={label}>Type</span><select style={input} name="type" defaultValue={bonus?.type??"welcome"}><option value="welcome">Welcome</option><option value="no_deposit">No deposit</option><option value="free_spins">Free spins</option><option value="reload">Reload</option><option value="cashback">Cashback</option><option value="vip">VIP / Loyalty</option><option value="other">Other</option></select></label>
 <F n="promo_code" t="Promo code" v={bonus?.promo_code}/><F n="amount" t="Amount / offer" v={bonus?.amount} p="100% up to €500"/><F n="free_spins_count" t="Free spins" v={bonus?.free_spins_count} type="number"/><F n="min_deposit" t="Minimum deposit" v={bonus?.min_deposit}/><F n="wagering_requirement" t="Wagering" v={bonus?.wagering_requirement} p="35x"/><F n="eligible_countries" t="Countries" v={(bonus?.eligible_countries??[]).join(", ")} p="GB, CA, DK"/><F n="expires_at" t="Expiry" v={bonus?.expires_at?String(bonus.expires_at).slice(0,16):""} type="datetime-local"/><F n="terms_url" t="Terms URL" v={bonus?.terms_url}/><F n="affiliate_tracking_url" t="Bonus affiliate URL" v={bonus?.affiliate_tracking_url}/>
 </div>
 <label><span style={label}>Short terms / notes</span><textarea style={{...input,minHeight:80}} name="terms" defaultValue={bonus?.terms??""} placeholder="Important restrictions only"/></label>
 <div style={{display:"flex",gap:18,flexWrap:"wrap",color:"#dbe3ee"}}>{[["active","Active",bonus?.active??true],["featured","Featured",bonus?.featured??false],["new_players_only","New players only",bonus?.new_players_only??true]].map(([n,t,c]:any)=><label key={n}><input type="hidden" name={n} value="false"/><input type="checkbox" name={n} value="true" defaultChecked={c}/> {t}</label>)}</div>
 {[["status",bonus?.status??"active"],["bonus_percentage",bonus?.bonus_percentage],["free_spins",bonus?.free_spins],["free_spins_value",bonus?.free_spins_value],["max_bonus",bonus?.max_bonus],["max_cashout",bonus?.max_cashout],["game_restrictions",bonus?.game_restrictions],["eligible_states",(bonus?.eligible_states??[]).join(", ")],["seo_title",bonus?.seo_title],["seo_description",bonus?.seo_description],["source",bonus?.source??"manual"],["source_url",bonus?.source_url],["sort_order",bonus?.sort_order??0]].map(([n,v]:any)=><input key={n} type="hidden" name={n} value={v??""}/>)}
 <input type="hidden" name="no_deposit" value={bonus?.no_deposit?"true":"false"}/><input type="hidden" name="deposit_required" value={bonus?.deposit_required===false?"false":"true"}/><input type="hidden" name="exclusive_offer" value={bonus?.exclusive_offer?"true":"false"}/>
 {state?.error&&<div style={{color:"#fecaca"}}>{state.error}</div>}<div style={{display:"flex",justifyContent:"space-between",gap:10,paddingTop:10}}>{bonus?.id?<button type="button" className="secondary-btn" onClick={async()=>{if(confirm("Delete this bonus?")){await deleteBonus(bonus.id);router.push("/admin/bonuses");router.refresh()}}}>Delete</button>:<span/>}<div style={{display:"flex",gap:10}}><button type="button" className="secondary-btn" onClick={()=>router.push("/admin/bonuses")}>Cancel</button><button className="primary-btn" disabled={pending}>{pending?"Saving...":"Save Bonus"}</button></div></div>
 </form></div></div>
}
